### ISSUE TITLE
간단 글쓰기 사용시..

### ISSUE THREAD

**Issue by mactopia** [phiDelbak/Board-DX-for-XE#10]
일반 글쓰기 버튼도 나왔으면 좋겠습니다. 즉, 유저가 편리한 쪽으로 이용에 맞길수 있으면 좋겠습니다.

간단하게 쓰고 싶은 사람도, 이미지도 첨부하며 길게 쓰고 싶은 사람도...편하게 쓸수 있도록요.!

**Comment by mactopia** [comment]
추가로 본문 읽기로 들어갔을경우에는 간단 글쓰기가 사라졌으면 좋겠습니다.

**Comment by phiDelbak** [comment]
네 참고 할게요.
앞으론 질문외 건의사항엔 답변은 생략 할게요.
다른뜻은 없고 어차피 다 참고할거니까 ㅋ;
