### ISSUE TITLE
리뷰 스킨 통해 매겨진 점수, 통계화 가능하면 좋겠네요.

### ISSUE THREAD

**Issue by saymehan** [phiDelbak/Board-DX-for-XE#106]
리뷰를 통해 매겨진 점수를 통계해서 점수화 할 수는 없을 런지요..

예를 들어 특정 식당의 전체적인 리뷰 점수를 계산한다거나 하는...
그러면 기왕에 매겨진 점수가 통계치를 통해 평균, 객관화될 수 있을 것 같습니다

제 경우에는 항공사 리뷰 게시판을 운영하고 싶은데,
이 경우 복수의 유저들이 각기 항공편 이용 시 마다 리뷰와 평점을 매기게 될 것이고,
그 데이타들이 집계된다면 특정 항공사의 평균 평점을 표시할 수 있지 않을까 싶네요.

그렇게 된다면 진정한 의미의 리뷰 스킨 기능을 가지게 되지 않을까요? ^^;;

잘 모르는 입장에서 의견 드린 것이니 얼토당토 않더라도 이해 부탁 드립니다. ㅎ

**Comment by phiDelbak** [comment]
유저들이 대한항공에 대한 리뷰를 작성하면 대한항공에 대한 리뷰들을 모아 특정 항목에 대한 평균값 혹은 그런 통계치 등을 계산해 보여줬으면 하신다는 말씀이신가요?

만약 그런것이라면 DX에서 제공한 리뷰 게시판은 딱히 어떠한 주제가 있는것이 아니고 추가되는 평점또한 그 주제에 따라 달라지기에 불특정 주제를 대상으로한 DX 게시판에선 제공할 수 없는 기능인것 같습니다.

**Comment by saymehan** [comment]
그렇군요.. 혹시 추가 개발이 가능하실 지 해서 여쭈었습니다.
다른 방안이 있는지 개인적으로 조금 고민해 봐야 겠습니다.

감사합니다.
