### ISSUE TITLE
리뷰 DX 게시판, 모바일에서 카테고리 표시 가능한지요?

### ISSUE THREAD

**Issue by saymehan** [phiDelbak/Board-DX-for-XE#108]
모바일에서 카테고리(분류) 표시가 제대로 나타나지 않는 것 같습니다.

예를 들어 PC 화면에서는 아래와 같이 좌측 글 제목, 우측 카테고리가 나타납니다.

![img2](https://cloud.githubusercontent.com/assets/13432451/8798429/24d9dc40-2fdd-11e5-88b5-1f100546f5e5.jpg)

하지만 모바일 화면에서는 카테고리가 나타나질 않네요.
상단에 카테고리가 있기는 한데, 경우에 따라서는 나타나기도, 나타나지 않기도 합니다.
(상단 카테고리를 클릭해 우측 사이드 바에서 선택하면 카테고리가 나타나지만, 글을 직접 클릭해 화면으로 볼 때는 카테고리가 나타나질 않습니다.)

![img3](https://cloud.githubusercontent.com/assets/13432451/8798430/28bde3f6-2fdd-11e5-8d73-831b95790f31.png)

감사합니다.

**Comment by phiDelbak** [comment]
모바일 목록에서 표시되기에 본문에는 따로 카테고리를 표시하는 코드를 넣지는 않았어요.
다음 버전까지 모바일 본문에서도 카테고리를 표시할지 고민해 보겠습니다.
(카테고리를 표시에 다른 의견 있으면 댓글 달아 주세요.)

참고로 모바일 상단에 카테고리가 경우에 따라 보이고 안보이고 하는것은 카테고리가 선택되었을때만 표시되기 때문입니다.
그러나 [모듈정보>옵션>**카테고리 추적**]을 **사용**하시면 모바일 상단에 해당 문서의 카테고리가 항상 표시됩니다.
다음 버전 전까지는 이렇게 **카테고리 추적**사용하셔도 됩니다.

**Comment by saymehan** [comment]
그렇군요. 다음 버전에 예쁜 카테고리 봤으면 합니다. ^^ 감사합니다.
그리고 카테고리 추적으로 일단 상단에 보이니 어떤 분류에 해당하는 글인지 알 수 있어 다행입니다.

저 같은 사용자들은 파이델 님 같은 개발자들이 계셔서 천군만마 네요.
다시 한번 감사 드립니다.
