### ISSUE TITLE
블로그 스킨 댓글 폼 변경

### ISSUE THREAD

**Issue by ysuelvis** [phiDelbak/Board-DX-for-XE#129]
안녕하세요.
블로그스킨을 설치하고 테스트중입니다.
전 반응형 레이아웃 one color 를 사용하고 있는데
모바일에서 댓글 폼디자인이 이상해집니다.
그래서 댓글 폼을 위지윅으로만 사용할 수 있게끔 하면
모바일에서도 멋있게 나타납니다.
댓글 폼에서 html 이런거 선택사항없이

**Comment by ysuelvis** [comment]
글작성하다가 잘못저장이 되었는데 삭제는 어떻게 하나요?
삭제가 없어요. 죄송해요.

**Comment by Lastorder-DC** [comment]
close하시면 됩니다.

**Comment by ysuelvis** [comment]
감사합니다.^^ 
깃허브는 사용하기 힘들어요.
