### ISSUE TITLE
모바일도 별도로 목록수,페이지수,댓글수를 지정할수 있으면 좋겠습니다.^^

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#16]
반갑습니다. 다름이 아니라 사용하다보니..

기본게시판에는 불편한 점중 하나가 pc형과 모바일형의 목록수,페이지수,댓글수를 같이 사용하고 있습니다. 이것이 분리되면 정말 좋겠습니다. ^^ 가능할까요..별도의 모듈이라 검토 부탁드립니다. 

환영합니다. 좋은 게시판 모듈로 발전하길 바래요^^

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/b5c6f0e1c41b957900967afffc710acc325d7cc1
