### ISSUE TITLE
열람제한 - 보기 포인트설정시 제대로 구동이 안됨

### ISSUE THREAD

**Issue by yousel** [phiDelbak/Board-DX-for-XE#17]
포인트 제한 설정하고 "제한-보기" 포인트으로 설정 후

게시자가 포인트걸고 게시하면 포인트가 차감되고 게시가 잘 되나

열람하는 회원들은 포인트 차감없이 열람이 되는 문제가 있음

댓글설정시에는 잘 작동함.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/a978c07c16fa1edeee576e9f8b25713438974a69
