### ISSUE TITLE
분류 추가시 버그

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#18]
분류 추가할때나 삭제할때 
삭제할거냐고 계속물어봅니다.
삭제가 되기는 하지만.. 물어보는게 무한반복중

**Comment by phiDelbak** [comment]
해당 현상을 재현하지 못하였습니다.
언제, 어떻게, 코어버전, DX버전, 스샷, 등  좀더 자세히 적어주세요.

**Comment by unamnam** [comment]
코어버전 : 1.8.1
DX버전 : 1.9.1
내용 : 분류관리에서 분류의 X표시를 누르면 삭제하시겠습니까?
라는 메세지가 뜨는데 이 메세지를 취소나 확인을 눌러도 한 10번정도 물어봅니다.

**Comment by phiDelbak** [comment]
음... 1.9.1로 다운 후 테스트하였지만 역시 재현이 안되네요.
메세지가 뜨고 바로 새로고침되는 문제가 있기는 하지만 이건 xe코어의 문제이고...
특정 상황 특정 환경에서 발생하는가 본대요.
현재로선 버그가 발생할때까진 지켜봐야할 문제같습니다.

**Comment by unamnam** [comment]
음.. 여러사이트중에서 한곳만 이문제가 나타난것으로 확인되었습니다.
다른점은 php버전이 5.3 버전이라는것..? (5.3.28)
그리고 1.9.8 버전올라오면서 위같은 현상이 아니라 
아예 분류추가가 안되는것으로 변경되었습니다.

**Comment by unamnam** [comment]
이건 최신버전올리니 해결되었습니다.
