### ISSUE TITLE
확장변수 설정 버그

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#19]
확장변수 단일선택 설정을 만든뒤 
1,2,3,4 로 만들었을때
글작성시 1,2,3을 선택해도 무조건 4를 선택하게됨

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/f29e4e20ab7e8e6d885aee9e8842ccb08b939989
