### ISSUE TITLE
반응형레이아웃 사용시 문제

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#20]
DX를 반응형레이아웃에서 이용할시 큰 문제가 없으나
약간의 개선이 필요합니다.

1. 
모바일에서 볼경우 닉네임 조회수, 등록일 등이 다 차지해버려서 
제목이 안보이는 사태가 일어남...
일정크기로 작아질경우 닉네임과 조회수를 안보여주면 개선될듯 합니다.

2. 댓글 목록에서 닉네임은 보이나 댓글이 보이지 않습니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/a8c296db07bc7cbe73af227720826fb2fdc20c73
