### ISSUE TITLE
열람제한 - 게시자 글 수정시 문제

### ISSUE THREAD

**Issue by yousel** [phiDelbak/Board-DX-for-XE#22]
이전 열람제한 포인트 문제는 해결 된거 같습니다.

게시자가 100자이상 작성 후 게시자도 100자까지만 보이고 수정을 눌렀을 때에도 

100자까지만 나옵니다. 

하지만 다른 회원이 포인트획득 열람시 본문 전문 다 잘 보입니다.

포인트/댓글 제한 둘다 동일한 현상

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/0d5e2dfb5b95a2f0ce60ba409ee29ef2db864f1b

**Comment by phiDelbak** [comment]
빠른 버그 제보 감사해요. xe 자료실에 올렸으면 큰일날뻔^^
