### ISSUE TITLE
혹시 리스트에서 스크랩 기능가능할까요..

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#23]
원래는 본문에 스크랩버튼이 있는데요 목록에 스크랩버튼이 있어서 목록에서 스크랩하거나.

또는 내가 스크랩한 글 옆에는 표시가 되여 있거나..하는 기능이 있으면 좋겠습니다. ^^

회색 별이 있다가 클릭해서 스크랩하면 노란색 별로 스크랩 한 글을 리스트에서 표시해 주는 기능이 있으면 좋을 듯해서요..하하 기능 추가이니 천천히 고려해 봐주세요~~~

감사합니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/d36735849ac4873b6b3710112b6e47e467f1322f
일단 스크랩 표시 기능만 하였습니다.
