### ISSUE TITLE
글 수정시 카테고리 지정문제

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#24]
작성시에는 분류없음이 표기되어 분류값을 지정할 수 있게 되어있지만

1. 글수정시에는 분류없음이 표기되어 있지 않고
2. 글수정시 원래 지정한 분류가아닌 첫번째 분류를 선택하게 되어있습니다.

둘중에 하나를 개선하면 좋을듯 합니다.

**Comment by phiDelbak** [comment]
[단계형 분류]를 사용안할때 말씀이시죠?

확인하였습니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/dad8368463eb0d23f8df8963de6d21da94b1ae8e
