### ISSUE TITLE
닉네임 값은 필수입니다

### ISSUE THREAD

**Issue by prologos** [phiDelbak/Board-DX-for-XE#26]
1.9.1버전에서는 아무 문제가 없었는데 1.9.8로 업데이트 후 글쓰기나 수정시 "닉네임 값은 필수입니다"라는 alert창이 뜹니다.

**Comment by phiDelbak** [comment]
[캐시 재생성] 하셨나요?
해도 안되시면 1.9.1 다시 돌리셨다가 확인해보시고 1.9.8로 다시 업데이트해보세요.

**Comment by prologos** [comment]
네 캐시 재생성은 했습니다.
1.9.1로 돌아가니 이상없이 작동합니다. 그상태에서 다시 1.9.8로 올렸는데 다시 동일한 현상이 발생합니다.
대략적인 서버 정보 첨부합니다.

app : Microsoft-IIS/8.5
xe_version : 1.8.1
php : 5.6.8
db_type : mssql
use_rewrite : Y
use_db_session : N
use_ssl : none

**Comment by phiDelbak** [comment]
비회원으로 글써도 그런가요?
재현이 안되는 현상이라...
가능하면 글쓰기 가능한 테스트 주소 부탁합니다.

**Comment by prologos** [comment]
음... 비회원으로 글쓰기 허용하고 해봐도 동일한 alert 발생하세요.
http://a3ghost.dyndns.org/test_dx

**Comment by phiDelbak** [comment]
자바 충돌 일어나는거 같은데 레이아웃 빼주세요.

**Comment by phiDelbak** [comment]
원인 파악했어요
모달창 사용안하면 그러네요.
모달창 사용으로 하고 써보세여.

**Comment by prologos** [comment]
레이아웃 뺀상태에서 모달창 사용함, 사용안함 둘다 동일 증상 발생합니다.
혹시 변경된 부분중에 db 쿼리도 있나요?
mysql에서 그냥 사용하는 쿼리도 mssql쪽에서는 문제 되는 경우가 많아서... 혹시나해서 여쭤 봅니다.

**Comment by phiDelbak** [comment]
음... 에드온을 다꺼보라고 할수도 없고 ㅎ;
제 환경에선 재현이 도저히 안되네요. 
모바일에서도 그러나요? 그것만 까지만 확인해 주세요.

**Comment by prologos** [comment]
모바일에서는 회원, 비회원 모두 글쓰기 됩니다 ^^;;

**Comment by prologos** [comment]
ㅎㅎㅎ
애드온 하나하나 꺼가면서 테스트 했는데 jsecure_xe란 애드온과의 문제 인거 같네요.
해당 애드온 끄니 정상 작동합니다.

**Comment by phiDelbak** [comment]
어 방금 딱 JSecureXE SSL 이거 꺼보라고 하려던 참이었는데 ㅎㅎ
