### ISSUE TITLE
scm 플레이어 사용시 문제

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#28]
SCM 플레이어 애드온 사용시에
글작성을 하면 작성은 되지만
작성페이지에서 목록페이지로 넘어가질 않습니다. 
(글삭제시에도 마찬가지)

기본게시판은 정상적으로 작동하는걸로 봐서는
DX와 뭔가 충돌이 일어나는것 같습니다.

**Comment by unamnam** [comment]
위에꺼 연장선으로
하단에 프레임 추가시 (예, 주소 고정 애드온 Type.1 사용시)
메인페이지로 돌아갑니다.

**Comment by unamnam** [comment]
내용 약간수정
프레임과 관련된 애드온이나 직접프레임 사용시 문제 발생하는듯 합니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/996314f68ecd070f02b64dd704f01f0fa8c09e79
