### ISSUE TITLE
DX에서 XE로 모듈바꾸기 문제

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#29]
DX에서 XE로 변경시에 딜레이가 존재합니다.
예전에는 없었던것으로 기억하는데 요번에는 변경해보니 
첫 목록부분딜레이, 글쓰기부분이 바뀌는데 오래걸리는것 같습니다.
그리고 모듈변경할때 체크박스 선택할때 전체선택이 안되고 있습니다.

**Comment by phiDelbak** [comment]
아마도 캐시가 생성되면서 발생하는 딜레이 같습니다.
캐시 생성 이후엔 괜찮아 질거라 생각합니다.
