### ISSUE TITLE
구DX에서 신DX변경시 문제

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#30]
구DX에서 신DX로 변경시에  추천버튼이 정상적으로 작동되지 않는데
(잘못된 요청입니다. 문구가 뜸) 캐시파일 재생성해도 같은 문제발생 

모듈바꾸기로 DX에서 기본게시판을 한번 변경했다가 다시 DX로 돌아오면
추천기능이 되살아납니다.

**Comment by phiDelbak** [comment]
게시판 설정을 새로 저장해주세요.
