### ISSUE TITLE
모바일 개선필요

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#31]
모바일모드에서 글을 클릭할경우 
현재는 글만 보여지고 있는데
PC처럼 글하단에 목록이 출력이 되게 가능해졌으면 좋겠습니다.

**Comment by phiDelbak** [comment]
비슷한건 있어요
모바일 정보 > 이전/다음 목록 수

**Comment by phiDelbak** [comment]
이전/다음 목록 수로 대처
