### ISSUE TITLE
포인트 채택시 관리자 채택요청

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#32]
포인트 채택 기능 사용시
채택을 하지 않는 사람을 위해서
관리자가 채택할 수 있었으면 합니다.

**Comment by yousel** [comment]
괜찮은 아이디어 같은데욤?

**Comment by Syangki** [comment]
괜찮은 아이디어네요
아니면 날짜제한을 두어서 몇일이지나면 자동채택이 된다거나..

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/fd97361e8bc5cd5e9743361be175a6e031e72749
