### ISSUE TITLE
ajaxboard 모듈과 호환...or 자체적으로..

### ISSUE THREAD

**Issue by Syangki** [phiDelbak/Board-DX-for-XE#33]
제목을 어떻게 해야될지 몰라서 ㅎㅎ

댓글달때, 대댓글을 달때, 댓글페이지네이션 넘길때,추천,비추천을 할때

새로고침이 안되었으면 합니다.

이슈에다가 남겨도 될지모르겠네요 ㅎㅎ

**Comment by phiDelbak** [comment]
추천,비추천은 새로고침 안되요.
댓글 ajax는 그걸 고려해 만든 스킨이 아니기 때문에 좀 복잡해져서 
추후 ajax 전용 스킨을 따로 만드는게 더 좋아보여요.

**Comment by Syangki** [comment]
흠.... 그렇군요 장단점을 말씀하셨는데 단점이있나요??

**Comment by phiDelbak** [comment]
아. 제가 코딩 하는데 필요한 장단점을 말한거예요 . ㅎ;
ajax 로 댓글 filter 를 만들어야 하는데 스킨이 ruleset 에 맞게 제작해서요
같이 쓰려니 에드온 충돌이 일어나고... (최근에 같이 써서 캡차 에드온과 충돌중... 다음 버전에 고쳐질 예정) 머 이런저런 개인적인 장단점을 말한거예요 . ㅎ;

**Comment by phiDelbak** [comment]
ajaxboard 호환은 ajaxboard가 먼가 봤는데 대응 플러그인이 있더군요.
자세히 살펴보진 않았지만 대응 플러그인이 존재하는걸로 봐서는 아마도 그 제작자님이 플러그인을 만들어 주는게 더 나은 방향 같습니다.

**Comment by unamnam** [comment]
추천 비추천은 모듈로 DX에서도 사용 가능합니다. 
새로나온 모듈 써보세요. 
댓글 대댓글은 어쩔수 없겠네요

**Comment by Syangki** [comment]
음 그렇군요 말씀하신거 보니 일리가있네요 ㅎㅎ
