### ISSUE TITLE
반응형 이용시 문제 

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#34]
1.9.9 버전 깔아보았습니다.
모바일 미적용시 (반응형시) 
댓글부분은 수정되었고
제목부분도 잘나오긴한데 
번호 , 닉네임 , 조회수 , 등록일 등등이 세로로 길게 출력됩니다.

2
0
1
5
0
5
1
2 
이런식으로 출력이 되버리네요..

**Comment by phiDelbak** [comment]
이게 사실은 감추면 글이 안보여서 그냥 그렇게 둔건데요
잘라보여주는게 더 나은가요?

**Comment by unamnam** [comment]
잘라보여준다는건 이전처럼 돌아간다는 걸까요?

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/0034cc9f2e138e64717d862829d7bb71994ce676
