### ISSUE TITLE
연속글 방지기능

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#35]
한사람이 하루에 많은 글을 쓸 수 없도록 게시판별로
1. 하루에 적을 수 있는 게시물 제한 (갯수지정)
2. 하루에 적을 수 있는 댓글 제한 (갯수지정)
기능이 있음 좋을것 같습니다. 
애드온으로 있는데 DX에서는 작동을 안하는듯 하네요

**Comment by phiDelbak** [comment]
애드온이 있으니 애드온 제작자분에게 업데이트 요청하시는게 더 좋을것 같습니다.
물론 DX 에 일부 기능도 에드온으로 있지만 그건 DX 가 먼저 시도한 기능이라 제외 ㅎ

**Comment by unamnam** [comment]
업데이트된지한 4년된거라서요..ㅋㅋ ㅠㅠ  
답변 감사합니다.
