### ISSUE TITLE
비회원 글작성시 버그

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#36]
비회원일경우 글을작성할때 
잘못 입력했습니다라는 문구가 뜨면서
글작성이 되지 않습니다.

**Comment by phiDelbak** [comment]
캡차 에드온 사용중이시죠?
수정도 커밋도 이미 완료되있으니 급하시면 메인페이지서 다운로드 받으면되요.
https://github.com/phiDelbak/Board-DX-for-XE/commit/184f033122296a7be6568beb99744e206fecc944

**Comment by unamnam** [comment]
받아봤는데 비회원 부분은 수정되었습니다. 감사합니다. 

아래는 없던 문제가 생긴부분입니다.
글작성하고 난후 빨간표시로 문서번호값은 필수입니다.라고 뜨고
댓글내용에 글내용작성했던게 노출됩니다. 
http://image.kilho.net/8gIZ

그리고 프레임추가시 글작성할때 안넘어갔던부분도 수정이 되었는데
SCM플레이어사용시에는 해결이안되었습니다. 
오히려 글작성창까지 안보이고 레이아웃의 드롭메뉴까지 작동을 안하고있습니다.
http://image.kilho.net/8gJ7

**Comment by phiDelbak** [comment]
음... 사진으로 바서는 원인 파악이 안되네요.
에드온을 하나씩 꺼보고 테스트해주세요.
그래도 안되면 오류가 나는 실 주소를 적어주세요.

**Comment by unamnam** [comment]
is4975@gmail.com 여기로 메일보냈습니다.

**Comment by phiDelbak** [comment]
음 살펴봤는데요
패치전 자바 파일이 그대로 사용중이네요.
캐시 재생성 하셧나요?

**Comment by unamnam** [comment]
다시 받으니 잘되네요! 감사합니다.

첫번재문제는 애드온문제였네요. 
이미지 자동출력 애드온 (auto_image)
을 사용하면 저렇게 나옵니다. 
메일로 첨부해서 보내드렸습니다.

**Comment by phiDelbak** [comment]
몇일전 다른거 하면서 이걸 빼먹었네요. ㅎ;
수정되었습니다.
https://github.com/phiDelbak/Board-DX-for-XE/commit/f314c8cd3f90bd6f427efa64e6b4a8074d5b728a
