### ISSUE TITLE
모바일모드시 버그

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#37]
게시판 제목
게시판 부제목 
게시판 설명

이부분에 글씨를 넣어도 PC에서는 정상작동하나
모바일모드에서는 적용이 되지 않습니다. 
구DX에서 적용했던게 적용이되고 바뀌질 않네요.

**Comment by phiDelbak** [comment]
모바일은 모바일 스킨 정보에 있어요.

**Comment by unamnam** [comment]
모바일정보 말씀하시는건가요? 
선택하신 스킨이 없습니다라고 나옵니다 ㅠ..

**Comment by phiDelbak** [comment]
메뉴에서 만든건 스킨이 가상 스킨이라 그래요.
모듈 스킨에서 직접 선택하시면 되요.

**Comment by unamnam** [comment]
모듈정보 스킨정보 모바일정보 이거말고 다른게있나요?
게시판에서 접속해도 모바일정보는 안들어가지고
다른곳엔 딱히 없는거같습니다.

**Comment by phiDelbak** [comment]
모듈정보 스킨요
![default](https://cloud.githubusercontent.com/assets/12091900/7633906/6d425e60-fa92-11e4-9313-a7c45cec8125.PNG)

**Comment by unamnam** [comment]
음.. 그부분은 기본스킨으로 지정되어있는데..
아래쪽에 모바일과 스킨타입이 나오는것말걸로 바뀌고
게시판제목을 지정하는곳은 없는것 같습니다. 

기본스킨으로 변경후에도 모바일정보가 접속되지 않고 있고
게시판제목과 설명을 바꿔도 모바일에서는 변경되지 않고있습니다!

**Comment by phiDelbak** [comment]
dx 음... 음... 최신버전이지요?
 이상하네 이유가 없는데...
사이트 기본스킨 사용 으로 돌려서 저장하신후
다시 기본 스킨으로 변경해보세요

**Comment by phiDelbak** [comment]
그래도 안되시면 테스트용 주소와 테스트용 관리자 아디/비번 메일 주세요
바드릴게요

**Comment by unamnam** [comment]
메일 보냈습니다 !

**Comment by phiDelbak** [comment]
static.analytics.openapi.naver.com
이거 머죠? 이게 계속 오류를 만들어 냅니다.

**Comment by phiDelbak** [comment]
크롬 에선 사이트 로그인이 계속 풀려버리네요.
파폭에선 되긴 하는데... DX가 최신이 아니네요?
최신으로 바꿔 보세요.

**Comment by unamnam** [comment]
2.0 올려도 동일합니다..끄응...   
위에오류는 뭔지모르겠네요.. 네이버관련된건 .. 애널리틱스 꺼보았습니다. 

테스트라고 적은 게시판 제목부분에 1,2,3 모바일에 노출되지 않고있고
모바일정보 역시 접속되지 않고있습니다. 
다시 확인부탁드려요.

**Comment by phiDelbak** [comment]
이거 받으시고요.
이름을 
beluxe.admin.view.php
이렇게 바꿔주시고요
modules\beluxe 폴더에 넣어 주세요 확인좀 해볼게요.

![beluxe admin view](https://cloud.githubusercontent.com/assets/12091900/7657054/e6b6b480-fb69-11e4-8431-c5cfe8a62612.jpg)

**Comment by unamnam** [comment]
넣었습니다!

**Comment by phiDelbak** [comment]
이거 받으시고요. [우클릭 다른이름 저장]
![beluxe admin view](https://cloud.githubusercontent.com/assets/12091900/7657243/5e378e70-fb6b-11e4-8b3a-d1edd24d4e8a.png)

이름을 
beluxe.admin.view.php
이렇게 바꿔주시고요
modules\beluxe 폴더에 넣어 주세요
이러면 아마 될거같은데

**Comment by unamnam** [comment]
음... 되지는 않지만 문구가 변경되었습니다.
./modules/beluxe/m.skins/../skins/default/mobile

**Comment by phiDelbak** [comment]
음 결로인식을 못하네요.
대충 알겠습니다.
수정해 올릴게요

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/2adb3de9fc2a4cdc690680d8be7b72f08550ed53
