### ISSUE TITLE
미채택질문,채택질문 분류추가

### ISSUE THREAD

**Issue by yousel** [phiDelbak/Board-DX-for-XE#38]
내글,내답변 처럼 , 아직 채택이 안된 질문만 볼 수 있는 미채택질문 컬럼

채택이 된 채택질문 컬럼이 별도로 추가되었으면 합니다.

*채택여부 기준으로 포인트색상이 변경되는 걸으로 보면 가능하지 않을 까 싶음

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/f1776c4754e10f8b8e91ae0eed20171c87a15357
