### ISSUE TITLE
채택/미채택/내글/내답변 선택시 변수명노출

### ISSUE THREAD

**Issue by yousel** [phiDelbak/Board-DX-for-XE#39]
검색박스에 변수명이 노출되는 현상 발생

![20150515_203557](https://cloud.githubusercontent.com/assets/12287957/7652045/9d2311e6-fb42-11e4-9c9e-18cccb483890.png)
![20150515_203625](https://cloud.githubusercontent.com/assets/12287957/7652046/9d23c6d6-fb42-11e4-9857-d4d949faf8e7.png)

**Comment by phiDelbak** [comment]
딱히 상관 없어서 그냥 둔거예요.
어차피 주소에 다 보여요

**Comment by phiDelbak** [comment]
포인트 사각 박스 꾸며주니 더 이쁘네요. 
너무 기능에 집중하다보니... 전 신경을 못써서... 나두 좀 꾸며 둬야겠다 ㅎㅎ ;

**Comment by yousel** [comment]
오..변수명에 언어추가해주셔서 감사합니다.
DX의 지식인의 기능을 거의 갖추고 있어서
Naver 지식인을 모방하여 커스텀을 진행 중 입니다..흐흐
