### ISSUE TITLE
채택시 포인트 조건문 발동 안함

### ISSUE THREAD

**Issue by yousel** [phiDelbak/Board-DX-for-XE#40]
질문자가 포인트 걸고 질문을 게시

채택시 포인트를 답변자하고 %씩 나눠어 가져야 하나, 

질문자에게 100% 환급됩니다.

Ver 2.1에서 버그확인.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/a7fdaddcb7681c74a16420bf483d3ce253f3634f
헉 이런 심각한 버그가...
끝났다 생각했는데 다시 버전 올려야 겠네요 ㅜㅜ
