### ISSUE TITLE
검색시 수정되었으면 하는 사안

### ISSUE THREAD

**Issue by botserv** [phiDelbak/Board-DX-for-XE#41]
검색시 제목+내용 검색이 되었으면 좋겠어요..

그리고 가령 제목으로 A란 검색을 해서 검색을 한뒤

내용으로도 검색해보고 싶으면 검색 버튼이 또 나와야하는데

취소 버튼이 나와서 변경 검색이 안됩니다. (그냥 검색후 엔터를 쳐야..)

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/343a5798816729ecfdd6541e584ac0675bd17e3b
