### ISSUE TITLE
글 내용도 목록에서 모달창으로..

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#42]
현재는 글쓰기만 모달창으로 가능한데요 본문 내용도 리스트에서 글을 클릭하면 모달창으로..

가능하면 좋을듯합니다..^^ 천천히 고려 부탁드립니다..............................................

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/d063e92884ebc61c4fd0e1fb36cb6b089dfdda6c

**Comment by ppleo** [comment]
글쓰기 / 글보기 모달창 두개다 안되는것 같습니다. ^^ 버전 2.2

**Comment by phiDelbak** [comment]
아직 배포는 안했습니다.
사용해 보시려면 2.2 가 아닌 메인 페이지에 있는 개발 버전을 받으셔야합니다.

**Comment by ppleo** [comment]
오잉..메인의 개발 버전을 받았는데 이상하네요....그럼 다음버전에서 확인할게요 ^^
