### ISSUE TITLE
컬럼이동시 검색문제점

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#43]
컬럼설정에서
제목위로 무언가를 올리면 검색할때 첫지정이 해당컬럼으로 변경됩니다.
예를들어 닉네임을 제목위로 올려두면 
검색할때 닉네임부터 선택이 되어있어서 검색이 안되는줄 알더라구요.

검색시 첫지정을 무조건 제목으로 되게끔하는게 좋을듯 합니다.

**Comment by phiDelbak** [comment]
제목+내용을 상단에 올리는것으로 대처
