### ISSUE TITLE
모바일모드에서 댓글풀기

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#45]
모바일모드에서 
댓글과 댓글쓰기가 클릭하기전에 가려져있는데

카테고리 다른글처럼
처음부터 풀어져있는 기능이 있으면 좋을듯합니다.

기본게시판은 풀어져있는데 
DX로 변경했더니.  불편하다는 사람이 많이있네요..

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/84500002b7084ec7ea4e1dcd2c6178ab91bb7681
