### ISSUE TITLE
스크랩 표시기능

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#46]
DX에서는 특이하게 스크랩표시기능을 지원하니
스크랩을 조금 더 활용할 수 있도록
추천 / 비추천 / 신고 옆에 스크랩도 표시되면 좋을듯 합니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/76617f2ab5deb7a137d37fa4e1fa5ba223ab0c0a
