### ISSUE TITLE
찬성 반대 댓글이용시 버그

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#47]
1. 찬성반대 댓글이용시 PC에서 베스트댓글이 나타나지 않고있습니다.
2. 댓글을 1개 적으면 댓글입력창이 보이지 않습니다. (PC에서)

**Comment by phiDelbak** [comment]
버그는 아니고요
주제에 대한 의견을 한번만 작성할수있고요. 그아래 대댓글로 의견을 더 추가하는 구조입니다.
또한  베스트 댓글은 토론형에 베스트글이 필요한가? 해서 베스트 글에 대한 처리를 아직 안했어요.

**Comment by unamnam** [comment]
아.. 그런식의 느낌이군요. 알겠습니다.
근데 버그는 있습니다.
찬성에 하나를 적으면 반대에도 하나를 적어야 진행이되는데
하나만 적어도 바로 댓글창이 없어집니다.

**Comment by unamnam** [comment]
아 다른회원이 채워야 되는거군요. 버그가 아니네요.
