### ISSUE TITLE
포인트팡팡 모바일에서 문제점

### ISSUE THREAD

**Issue by unamnam** [phiDelbak/Board-DX-for-XE#50]
포인트팡팡 이용할때
글자색에 font color를 넣었을경우
PC에서는 문제없이 출력되지만

모바일사용자가 당첨되었을때는
댓글에 그대로 태그가 노출됩니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/point_pangpang/commit/0ccd779fb2799f62087337cc3ddada73bf206420
