### ISSUE TITLE
1.8버전에서 모달창 사용시

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#51]
1.8버전에서 모달창(ck에디터,IE10) 사용시
에디터창에 커서가 먹히지 않는 현상히 빈번히 일어나는 것 같습니다.

여러 컴에서 확인했는데요. 
로딩시 글쓰기가 가능할 때도 불가능할 때도 있는것 같습니다.
입력창에 마우스를 클릭하면 커서가 생기지 않습니다.

모달창 기능이 너무 편리해서 좋은데요.
확인부탁드릴께요~

**Comment by phiDelbak** [comment]
잘되었네요. 그렇지 않아도 요즘 모달창 코드 관련 업데이트 중 인데요.
메인 페이지 우측 하단에 [Download ZIP] 이라는 버튼을 눌러 제일 최근에 커밋된 파일을 받아 설치해 테스트 해주세요.
설치후 [캐시 재생성]은 꼭 해주세요.

**Comment by jungbm80** [comment]
네. 감사합니다.
지금 설치하였고요. 위 이미지처럼 설명창 상단이 블랙으로 표시되었습니다^^
모달창으로 변경 후 테스트로 글 몇 개 작성해보았는데
현재 별 무리없이 정상 작동하고 있습니다~
꾸준히 사용하면서 문제되는 부분이 생기면 또 알림드리겠습니다.
너무너무 감사합니다.

**Comment by jungbm80** [comment]
![default](https://cloud.githubusercontent.com/assets/12507367/7782236/61c5e24a-0146-11e5-9b6b-61aea906c32a.jpg)

개인적인 의견인데요.
본문의 글쓰기가 시작되는 부분에
미관상 여백(좌측여백, 상단여백)이 필요할 것 같습니다.
왼쪽 줄에 글씨가 붙어서요.
별문제는 아니지만, 긍정적으로 검토부탁드릴께요~~

**Comment by jungbm80** [comment]
![default](https://cloud.githubusercontent.com/assets/12507367/7783737/6b53232c-0187-11e5-81e5-ed136ca2a9fa.jpg)

게시판 글제목부분에서 한글이 깨져나오는데요.
혹시 제 컴에만 문제가 있는 걸까요?
글꼴 문제인거 같은데요. 의견부탁드립니다~

**Comment by phiDelbak** [comment]
스킨정보 제일 밑에 사요아 CSS 라고 있어요 거기에 

#siMaTitle h1.mai a {font-family: 굴림,돋음체;}

이렇게 적고 저장해 보세요.

**Comment by jungbm80** [comment]
네 감사합니다. 글꼴 문제는 해결되었습니다.

그리고 모달창 로딩중 커서가 안먹히는 현상이
대략적으로 5번 글쓰기중 1~2회 정도 발생하는 것 같습니다.
원인이 뭘까요?ㅜㅜ

그리고, 현존하는 게시판 중에 DX가 최고인 것 같습니다.
진짜 오아시스를 만난 기분이예요~ㅎㅎ

**Comment by phiDelbak** [comment]
보통 그런경우 충돌이 원인일 경우가 많아서
게시판을 임시로 테스트용으로 하나더 만드시고 그 게시판은 레이아웃을 빼고 에드온을 기본 에드온외에 다 끈상태에서 하나씩 키며 테스트해보세요.

**Comment by jungbm80** [comment]
레이아웃 빼고, 모든 애드온 빼고
순수 게시판(xe 1.8.2)으로만 테스트 해보았는데요.
동일한 현상이 발생합니다.

혹시 인터넷 상태도 문제가 될 수 있을까요?

**Comment by phiDelbak** [comment]
브라우저를 크롬으로 한번 써보세요.
그것도 아니면 에디터를 xpresseditor 로 사용해 보세요.
둘다 아니면 테스트 가능한 주소를 메일로 보내주시면 직접 살펴볼게요.

**Comment by jungbm80** [comment]
네. 감사합니다.
문서 서식부분을 'XE CKEditor 기본서식'으로 바꾸니 해결되었습니다.
------------------------------------
모달창 로딩시 본문에 커서가 안먹히는 현상은
마우스 클릭을 본문이나 확장변수 입력창에 하면 커서가 안 찍힙니다.

그런데 여기서 에디터창의 기능버튼(아이콘)을 누르면 커서가 활성화가 되고요.
글자관련 아이콘만 눌렀을 때 커서가 나옵니다.
글자와 상관없는 소스보기, 이모티콘을 누르면 커서가 안먹히고요.
(에디터 컴포넌트는 모두 사용해제하고 테스트해보았습니다
현재 기본 컴포넌트는 사용 또는 사용해제와는 무관한것 같습니다.)

테스트URL: http://philgo.co.kr/test1

**Comment by phiDelbak** [comment]
윈도우 7에서 익스11,크롬,파폭 브라우저에서 10번 이상씩 글쓰기를 시도하였으나 해당 문제를 찾을 수 없었습니다.
혹시 다른 컴퓨터 있나요? 다른컴에서도 그러나요?

**Comment by jungbm80** [comment]
네. 에디터 xpresseditor에서도 동일한 현상이 발생합니다.
다른 컴에서도 동일하고요. 테스트 브라우저는 모두 익스10입니다.
 
그리고 크롬은 정상작동합니다.
파폭은 테스트를 하지 못하였습니다.

**Comment by phiDelbak** [comment]
익스 10 이 문제네요.
저번 처럼 최근 커밋된 [Download ZIP] 받아서 사용해보세요.

**Comment by jungbm80** [comment]
네. 감사합니다. 확인하였습니다.
스킨정보에서 모달창 사용안함(글쓰기/글보기 체크해제)으로 저장후에도
체크가 풀리지 않는 현상이 있습니다. (기능은 적상 작동합니다.^^)

글보기 모달창과 핫트랙 동시 사용시
제목링크부분에 커서가 닿으면 핫트랙이 사라지고 모달창 글보기기능이 해제됩니다.
혹시 의도하신바가 있으신건가요?^^

 * 모달창 글보기 부분의 검정색 상단부분에 'doc trb com'라는 문구가 보입니다. 
    혹시 몰라 전달드려요~

**Comment by phiDelbak** [comment]
의도는 아니고요. 아직 만드는중이라서 그래요 ㅎ
'doc trb com' 이것도 역시 트랙백,댓글 넣을 준비...
그런데
[제목링크부분에 커서가 닿으면 핫트랙이 사라지고 모달창 글보기기능이 해제됩니다.]
라고 하셨는데 제목링크부분이 정확히 어디를 말씀하시는건가요?

**Comment by jungbm80** [comment]
![img1](https://cloud.githubusercontent.com/assets/12507367/7787186/415f5dd0-0239-11e5-93a2-76e06adb5fff.jpg)

마우스 손가락표시가 캡쳐가 안되는데요.
핫트랙사용시 해당 글제목 영역위에 마우스 손가락이 있을 때 화면이고요

![img2](https://cloud.githubusercontent.com/assets/12507367/7787189/64a88dca-0239-11e5-8035-ed3ce559cbcb.jpg)

마우스 손가락이 글제목 위로 올라갔을 때 핫트랙(보라색 박스)가 사라집니다.

**Comment by phiDelbak** [comment]
혹시 호환성 모드 사용하세요?
저거 익스 9버전 부터 그러는건데...

**Comment by jungbm80** [comment]
아~ 그렇군요. 테스트는 호환성 모드 사용하지 않았고요.
호환성 보기에 웹사이트 추가하면 아예 핫트랙이 보여지지 않습니다.

개인적으로 <텍스트제목 클릭과 모달창 내용보기>보다는
<핫트랙 클릭과 모달창 내용보기>조합이 더 궁합이 맞는 것 같다는 생각입니다. 
핫트랙 클릭 후 좌측에서 모달창이 달려나와 펼쳐지면 좀 있어보이는 것 같습니다~

사실 모달창 글쓰기만 보다 모달창 글보기를 보니깐 너무 쓰고(보고) 싶습니다^^
가능하시면 IE10에서도 지원되게끔 힘을 실어주세요~

**Comment by phiDelbak** [comment]
익스 10 지원 방금 커밋 했어요. 받아 사용해 보세요.
사실 익스 10은 제가 테스트가 불가능해서 (익스 테스터기도 익스10만 지원안하다보니...)
익스 10은 순전히 제보에 의지해야 하기에... 혹시 모를 다른 오류가 있을 수 있어요. ㅎㅎ;

**Comment by jungbm80** [comment]
네. 너무너무 감사합니다^^
지금 테스트 해보았는데 진짜 최고인것 같습니다.ㅎㅎ
 
글제목 클릭시 모달창(보기)이 활성화되는 부분을
웹진이나, 갤러리 형태의 게시판에도 적용할 경우(핫트랙 기능해제)를 생각하여
썸네일부분에도 모달창보기 적용을 해주시면 보다 좋을 것 같다는 개인적인 생각입니다.

목록내 텍스트부분만 적용하고 썸네일 부분이 안된다면 일관성문제도 있는 것 같고요.
계획중이실수도 있겠지만 그래도 혹시 몰라 의견 드려보아요~~

많은 사이트 운영자들이 이 기능이 유용함을 아신다면
모달창 보기가 웹진이나 갤러리 형태에 많이 쓰일것 같습니다!
