### ISSUE TITLE
common.min.js 파일 IE 브라우저 파일첨부 오류

### ISSUE THREAD

**Issue by bm3222** [phiDelbak/Board-DX-for-XE#52]
안녕하세요

15년 4월달에 XE 사이트에 공유해주신 
Board-DX-for-XE 설치 시 
IE 브라우저에 글 작성 후 모달창 자동으로 종료 안되고 저장 후 모달창 화면에 작성된 글이 보이는 증상이 있는 반면 파이어폭스나 크롬에서는 정상적으로 모달창 동작이 잘 됨을 확인했으나

최근 Board-DX-for-XE 업그레이드 된 파일로 업데이트 되거나
https://github.com 사이트에 올려주신 Board-DX-for-XE-master
압축 파일을 설치하게 되면

오달창은 모든 브라우저에서 정상적으로 동작하는데
파일첨부 버튼이 활성화 되지 않는 오류가 생깁니다.

15년 4월 자료와 최근 업데이트 된 자료를 검수한 결과 
beluxe\skins\default\js\common.min.js

common.min.js 이 파일이 문제로 확인되었습니다.

최근 업데이트 해주신 파일 설치시 오달창은 모든 브라우저에서 정상 동작하지만
파일첨부 기능이 먹통이되고

예전 버전(15년 4월 등록자료)으로 설치시 모든 브라우저에 파일첨부 기능은 정상적이지만
IE브라우저에서 오달창 로딩 오류나 지연 증상이 발생해

최근 버전과 예전 버전 common.min.js 파일을 확인해 주셨으면 좋겠습니다.

현재 이러한 증산으로 저의 경우 
전체 파일은 최근 업데이트해주신 파일과 
common.min.js 파일은 예전 올려주신 파일로 올려 놓고 사용하고 있습니다.

오류 수정이 되시면 답변글을 joel74@naver.com 메일로도 부탁드립니다.

감사합니다.

**Comment by phiDelbak** [comment]
혹시 모르니 새로 커밋한 Board-DX-for-XE-master 파일 받아 사용해 보시고요.
익스 IE브라우저 버전을 말씀해주세요.

**Comment by bm3222** [comment]
제가 처음 올린 글에도 써놨듯이 
https://github.com 사이트에 올려주신 Board-DX-for-XE-master
파일로도 이미 설치해 봤었는데

같은 증상입니다.
제 컴 os는 윈7 32비트이고 브라우저는 IE 11입니다.
익스브라우저 외에 크롬, 파이어폭스에서도 최근 버전 Board-DX-for-XE-master  설치시
파일첨부 기능이 활성화 되지 않습니다.

4월달에 올려주신 파일로는 모두 정상적으로 되는데
IE브라우저에서만 모달창이 먹통이고 다른 브라우저는 모두 정상 작동 합니다.

**Comment by phiDelbak** [comment]
Board-DX-for-XE-master 파일은 커밋될때마다 매번 바뀌는 파일입니다.
정식이 아닌 개발 버전이니 전에 받은 거랑 상관없이 오늘 다시 받으셔야 합니다.

그리고 최근 커밋한 개발 버전에서 테스트한 결과 알래 그림처럼 해당 문제를 찾을 수 없었습니다.

![aaa](https://cloud.githubusercontent.com/assets/12091900/7826983/93a61de8-045c-11e5-8339-f624a52f7218.PNG)
![aaa0](https://cloud.githubusercontent.com/assets/12091900/7826985/9a6be504-045c-11e5-995d-fbfd4e9b2c04.PNG)

**Comment by bm3222** [comment]
답변주셔서 추가 답글 올리기 직전에 다운 받아 기존 폴더 다 지우고 
새롭게 설치 했는데 같은 증상이였거든요

다운로드 경로는 https://github.com/phiDelbak/Board-DX-for-XE
우측하단에 있는 Download.ZIP 파일이였습니다.

괜찮으시면 문제되는 common.min.js 4월에 올려주신 파일과
최근 파일 메일 회신으로 보내드려도 될까요?

common.min.js  파일만 4월걸로 올리면 파일첨부 활성화가 되는 상황이라
답답하네요 ^^';;

**Comment by phiDelbak** [comment]
common.min.js 보내주셔도 증상이 없으면 저도 고칠 수 없어요.
문제가 되는 게시판 주소를 알려주셔야 증상을 확인하고 원인을 찾아 볼텐데...
주소 불러 주시기 어려우면 모달창 사용을 중지 하시고 일반창으로 사용하시는 수 밖에 없을것 같습니다.

**Comment by ppleo** [comment]
저도 같은 증상이군요..^^ 그래서 모달창이 나오지 않았군요.

**Comment by bm3222** [comment]
같은 증상이 있었군요
모달창이 되면 파일첨부가 안되고 
파일첨부가 되면 모달창이 익스에서는 안되더라구요  ㅜ.ㅜ

**Comment by phiDelbak** [comment]
ppleo 님이 위에 올리신 사진 보고 알았습니다.
에디터가 xpresseditor 이거 사용하시더군요.

저는 항상 에드온,에디터,레이아웃 등 모든 설정을 기본값으로 테스트하기 때문에 그외 설정은 꼭 말씀해 주셔야 합니다. 
아니면 모든 상황을 추측에 의지해 테스트해야 하는데 그건 사실 너무 힘든 일입니다.

아무튼 증상을 찾았고 조만간 수정해 커밋하겠습니다.

**Comment by ppleo** [comment]
^^ 그렇군요. 다음부터는 테스트 페이지를 연결하거나 화면 캡쳐해서 알려 드리겠습니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/47b549eb61e05353ba9cbadc9cd009f2188dceee

**Comment by bm3222** [comment]
감사합니다 phiDelbak 님  ^^

정상적으로 동작 잘 됩니다.~ 성의있는 답변과 해결 감사드려요
