### ISSUE TITLE
태그 사용안할떄

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#53]
글쓰기에서 태그를 사용안할때  리스트에 나오는 태그리스트 버튼도 나오지 않아야 하지 않을까 합니다.

글쓰기에 사용하지 않는데 리스트에서 표시해 줄 표시 할 필요없을 듯합니다. 

확인 부탁드립니다.

**Comment by phiDelbak** [comment]
그냥 없으면 허전해서요.

**Comment by ppleo** [comment]
^^ 다른 방법으로 처리 해 보겠습니다. css만 건드리고 스킨을 다듬어 보고 있는데요..하다 보니.ㅋㅋㅋ

기능이 많아서 별도 스킨 만들기 무서워서..하하하

전체적으로 버튼 들에 아이콘이 부족한 것 같은데요..

http://xpressengine.github.io/XEIcon/ 를 사용해 보는것은 어떨까요..

**Comment by phiDelbak** [comment]
제가 아이콘이나 이미지를 잘 사용안하는 취향이라 그래요.
기본적으로 xe 에서 XEIcon이걸 사용 하는거라면 고려하겠지만 
일부 모듈이나 레이아웃 사용자만 사용하는것이기 때문에요.

버튼의 허전함을 멀루 채울 수 있을지 고민해 볼게요. (안할수도있어요)

**Comment by ppleo** [comment]
^^ 그렇군요 엡  고민 안하셔도 됩니다. 개발자님의 취향 존중합니다.

필요한 사람이 바꾸는거니..버그가 아닌이상 스킨 고쳐쓰는쪽으로 가시는것이 좋을것 같습니다.

저도 기본에 충실한 것이 좋다고 생각합니다. 항상 의견 듣어주셔서 감사합니다.
