### ISSUE TITLE
새로운 댓글 작성 돌아가기 버튼 누르면 css 적용이 안됩니다.

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#54]
새로운 댓글 작성시 act=dispBoardWriteComment 떄 돌아가기 버튼 누르면 

&act=dispBoardComments으로 가면서 css가 적용안되는 화면으로 나옵니다.

**Comment by phiDelbak** [comment]
자세한 상황을 설명을 설명해 주세요.

**Comment by ppleo** [comment]
![default](https://cloud.githubusercontent.com/assets/5974818/7850829/247f9dec-0522-11e5-9651-7413cb1eba21.png)
![2015 5](https://cloud.githubusercontent.com/assets/5974818/7850830/248426aa-0522-11e5-9617-e1f23a42cb0b.png)


크롬이고요. xe 코어 1.8.2 입니다.

**Comment by phiDelbak** [comment]
모달창이 아닐때 말씀하신거군요
확인하고 수정되었습니다.
https://github.com/phiDelbak/Board-DX-for-XE/commit/18cc159a23a69a9c4adb9f82d835d864d667d6fa
