### ISSUE TITLE
확장변수 값이 없을때는 확장변수 나오지 않는것이 좋을듯합니다.

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#55]
글쓰기에서 확장변수 값을 입력하지 않으면 본문보기시 나오지 않는것은 좋을듯합니다.

/beluxe/skins/default/_viw.list.html 101줄

<li loop="$exks=>$key,$val">
을
<li loop="$exks=>$key,$val" cond="$val->getValueHTML()">으로

**Comment by phiDelbak** [comment]
이것도 사실 취향 차이긴 한데...
스킨 옵션으로 넣어볼게요.

**Comment by ppleo** [comment]
^^ 그냥 두세요. 뭐 취향차이니..필요한사람은 바뀌겠죠..

**Comment by phiDelbak** [comment]
네^^
