### ISSUE TITLE
모바일 css body 배경 칼라

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#56]
body, .bd {
	background:#f8f8f8!important;
}

이것 때문에 모바일 레이아웃에 영향을 끼치는군요.

 .bd {
	background:#f8f8f8!important;
}
만 적용하는것이 좋을것 같습니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/89fd2bc63c0e23c1ac5ce289efd7010bbdb3507b

**Comment by phiDelbak** [comment]
수정했습니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/5db2d295433d7d4288808e4016e3f9b35bc23a21
