### ISSUE TITLE
간단히 글쓰기 시 체크 옵션 중앙정렬되는것.

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#57]
#siWrt .scWusr input {
  width: 16%;<-- 요거 삭제요..
  max-width: 120px;
}

혹시 주신 이유 있으신지요.현재는 아래 이미지 처럼 보입니다. 삭제 하면 왼쪽정렬로 됩니다. ^^ 확인요망!!

![3333](https://cloud.githubusercontent.com/assets/5974818/7852960/967827a6-0541-11e5-92ee-f48579883c03.png)

**Comment by phiDelbak** [comment]
아 그거 텍스트 박스만 해야하는데 버그네요 ㅎ

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/1cc28ac2257715825119016ba3660f060394e9b4

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/5db2d295433d7d4288808e4016e3f9b35bc23a21
