### ISSUE TITLE
모바일 스킨타입 설정관련

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#58]
모바일 개선사항 의견드립니다.
스킨타입 설정을 PC용이랑 Mobile용이랑 따로 설정해주셨으면 좋겠습니다.

PC용에서 스킨타입을 '목록'으로 설정 후 확장변수에 썸네일을 이용할 경우(썸네일+제목+확장변수)
모바일에서 같은 화면구성을 표현하기 위해서는 스킨타입을 '웹진'으로 선택해야 하는 상황입니다.
(목록에 간단한 확장변수 출력시 PC는 가로축의 활용이 유용하며, 모바일은 가로축이 짧기 때문에 세로축을 이용하는 편이 더 유용한 것 같습니다.)

모바일용 스킨타입 설정이 독립적으로 설정 가능하다면 보다 효율적인 표현이 가능하다고 생각합니다. 긍정적인 검토부탁드립니다.

아니면, PC용 스킨타입이 '목록'이더라도(썸네일 기능체크시)
모바일정보에서 썸네일 기능만이라도 이용할수 있는 옵션(일반/자동숨김)이 있으면 좋을 것 같습니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/7b746883017b673ac5fcf599f8283c91554e730c
썸네일표시시 모바일 웹진으로 변경되게 하였습니다.

**Comment by jungbm80** [comment]
네 감사합니다.
그런데 본 내용의 수정부분이 다음 업데이트시 반영되어지는건가요?
혹시 다음 업데이트(2.4 version) 시 다시 수정을 해야할런지 해서요~

**Comment by phiDelbak** [comment]
다음 버전에 반영되요 :)
