### ISSUE TITLE
모달창보기 왼쪽하단의 분류명보기

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#59]
![left](https://cloud.githubusercontent.com/assets/12507367/7925163/b48c1d7e-08fc-11e5-9e12-886a177a5119.jpg)

모달창 보기의 왼쪽 하단에 []:[분류명]으로 표기됩니다.
[]: =>가 잘못 노출된 것같습니다.

확인부탁드려요^^

**Comment by phiDelbak** [comment]
그러네요.^^ 수정되었습니다.
https://github.com/phiDelbak/Board-DX-for-XE/commit/b6a56929cb67162a478920b5f18cbb14bbb465c6

**Comment by jungbm80** [comment]
네~ 감사합니다^^
