### ISSUE TITLE
모바일 스킨 개선사항 - 목록의 기본변수 노출설정 관련

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#60]
모바일 스킨 개선사항 관련 의견드립니다.

게시판 기본변수의 보기/감추기 기능이 있으면 좋겠습니다.
확장변수까지 표현하기에는 공간에 무리가 있어 기본변수만이라도 설정가능하게 한다면 매우 유용하게 사용할 것 같습니다~

 - 분류 보기/감추기
 - 조회수 보기/감추기
 - 닉네임 보기/감추기
 - 등록일 보기/감추기

이런 구성도 나쁘지 않은 것 같습니다. 참고하시면 좋을 것 같아 캡쳐드려요~
![default](https://cloud.githubusercontent.com/assets/12507367/8017708/8ea88ce8-0c38-11e5-937b-429c4f5c9b15.jpg)

검토부탁드리겠습니다^^

**Comment by jungbm80** [comment]
그리고, 썸네일부분에 테두리부분이 없는 것이 더 깔끔한 것 같습니다.
지인 여러명한테 의견을 구했는데 테두리없는 편이 괜찮다고 피드백을 받았습니다^^

**Comment by phiDelbak** [comment]
모바일 이미지 테두리는 모바일 사용자 css에 이렇게 적으시면 없어집니다.
.lt.wz li.cb .thum{board:0}

**Comment by jungbm80** [comment]
네!! 감사합니다!^^

**Comment by phiDelbak** [comment]
메뉴얼은 아니지만 문의가 오면 이곳에 적어두고있습니다.
[게시판-DX-사용-팁과-질문들](https://github.com/phiDelbak/Board-DX-for-XE/wiki/%EA%B2%8C%EC%8B%9C%ED%8C%90-DX-%EC%82%AC%EC%9A%A9-%ED%8C%81%EA%B3%BC-%EC%A7%88%EB%AC%B8%EB%93%A4)
