### ISSUE TITLE
모바일 레이아웃 디자인 개선의견

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#61]
모바일 레이아웃 디자인개선 의견드립니다.^^
요즘 유저입장을 생각해보면 모바일 구현에 더 초점이 맞춰지는 것 같습니다~

![default](https://cloud.githubusercontent.com/assets/12507367/8017547/90dda480-0c33-11e5-9516-1cdf1ede8aed.jpg)

보통 레이아웃 영역의 색상이나 소소한 디자인에 따라 모바일의 전체적인 느낌이 결정되는데요.
모바일 DX스킨은 고정이라 기본게시판처럼 레이아웃에 맞춘 스킨으로 변경이 어려워
디자인적인 면에서 전체적인 스타일에 일관성을 맞추기 어려운 부분이 있는 것 같습니다.

하지만, 1번 영역과 2번영역의 배경색과 글자색을 유저가 레이아웃 색상에 맞춰 커스터마이징이 가능하다면 레이아웃과 어우러지게 모바일 레이아웃을 분위기를 그대로 가지고 갈수 있을 것 같습니다.

<우선순위 대로 기재함>
 - 흐름상 1번 영역과 2번영역의 위치가 변경되어야 할것 같습니다.
   (첫 로딩시 글제목과 큰글씨에 우선적으로 눈의 초첨이 가야하는데, 1번영역이 2번영역 위에 위치하는 것이 이를 방해합니다.)
 - 2번영역 글자색,배경색 변경가능
 - 1번영역 배경색 변경가능 or 배경색을 흰색으로 수정

여기까지만 구현된다면 현존하는 모든 모바일 레이아웃의 기본 스타일을 모두 소화가능한 DX스킨이 되지 않을까 생각합니다. 

지극히 개인적인 취향이지만
1번영역과 2번영역의 배경색이 모두 흰색일 경우가 깔끔하게 모든 레이아웃과 어우러지는 것 같습니다.
 
한번 살펴보시고 가능한 범위내에서 검토부탁드리겠습니다.~^^
제가 할수 있는것도 아닌데 넌지시 의견만 드리고 부담감만 드리는 것 같아
너무 죄송하고, 또 너무 감사한 마음입니다.

**Comment by phiDelbak** [comment]
디자인 색상에 관해선 취향 차이라 어떤게 좋을지 결정하기 쉽지않은 부분이 있어요.
다음 버전까지 고민은 해보겠지만 아직은 잘모르겠어요.

대신에 모바일 설정에 사용자 CSS 를 추가했습니다.
https://github.com/phiDelbak/Board-DX-for-XE/commit/be774d244fc78604c389149742a10251e3521b0d

사용자 CSS 에 스타일을 적어 자신만의 색을 지정할 수 있습니다.
사용예:
.st > h2,.pn,.sh,.bd{background:#fff}
.st > h2 a{color:#000}

**Comment by jungbm80** [comment]
네. 의견 반영해주셔서 감사합니다.
