### ISSUE TITLE
제목+내용 관련 이슈

### ISSUE THREAD

**Issue by botserv** [phiDelbak/Board-DX-for-XE#63]
일단 업데이트 감사합니다.

제목 + 내용 검색기능이 잘 정상적으로 작동되는 것을 확인하였는데요..

카테고리에 첫번째에 위치해있었으면 좋겠습니다.

또 모바일 버전에서는 제목 + 내용기능이 작동이 되지를 않는데,
모바일 버전쪽에도 해당 기능이 업데이트 되었으면 좋겠습니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/0a3b297cc739f9078ae97d062de9fa99a943593f
