### ISSUE TITLE
모바일에서 동영상 재생시 

### ISSUE THREAD

**Issue by airbogo** [phiDelbak/Board-DX-for-XE#64]
mp4를 피시에서 업로드 하고 나서 모바일에서 확인해보면 스케치북 스킨같은경우 플레이어 버튼이 표시되서 누르면 바로 재생이 되는데 dx게시판 모바일에서는 플레이어 버튼이 전혀 표시가 안되고 있습니다..

**Comment by phiDelbak** [comment]
기본 게시판에서는 확인해 보셨나요?

**Comment by airbogo** [comment]
아 죄송합니다. 확인해봤더니 모바일에서 미디어플레이어버튼이 가려져 있었네요 화면을 가로모드로 하니 플레이어 버튼은 나타 납니다... 번거롭게 해드렸네요
