### ISSUE TITLE
스킨타입 갤러리 적용시 이미지 클릭안됨

### ISSUE THREAD

**Issue by airbogo** [phiDelbak/Board-DX-for-XE#65]
목록형과 웹진형에서는 이상없으나 갤러리 타입으로 적용시 사진을 클릭해도 아무런 응답이 없습니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/11cfc60f1add2f65d54e7fc2e0ffd6a02f79b2b7
