### ISSUE TITLE
모바일 목록부분 - 확장변수 출력시

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#66]
모바일 목록부분에서 확장변수 출력시
<내용>출력을 하지 않을 경우 확장변수 내용과 조회수부분이 겹쳐지는 현상이 발생합니다.
그리고 확장변수를 URL로 선택 후 노출시키면 CSS가 먹히지 않는 것 같습니다.

테스트페이지(모바일로 접속하세요)
모바일 기본 레이아웃으로 테스트하였습니다. 
 >> http://******.co.kr/test1 (확장변수 타입을 "URL형식으로 선택함) 
 >> http://******.co.kr/cebu
 >> '텍스트'형식으로 선택하면 CSS가 먹히지만 글자겹침이 발생함.

모바일에서 URL형식 선택시 클릭이 안되더라도
텍스트형식으로 동일하게 보여줄 수 있는 방법이 있을까요?

**Comment by phiDelbak** [comment]
내용이 없으면 겹치네요 :)
다음 버전까지 모바일 사용자 CSS에 아래를 입력해 사용해주세요.
.lt.wz ul.ifo li.auth.cb {padding-bottom:20px}

그리고 URL형식 부분은 코어(xe) 버그가 있네요.
URL형식 사용시 a tag 중복 출력되는 버그가 있어요.
이거 코어 버그라 코어(xe) 이슈에 등록해 둘테니 고쳐질때까지 텍스트로 사용셔야 할거 같습니다.

**Comment by phiDelbak** [comment]
.lt.wz ul.ifo li.auth.cb {padding-bottom:20px}
.lt.wz ul.ifo li.auth a {display:inline;color:#777}

내용이 없으면 겹치네요 :)
다음 버전까지 모바일 사용자 CSS에 아래를 입력해 사용해주세요.
.lt.wz ul.ifo li.auth.cb {padding-bottom:20px}

그리고 URL형식 부분은 코어(xe) 버그가 있네요.
URL형식 사용시 a tag 중복 출력되는 버그가 있어요.
일단 코어(xe) 이슈에 등록해 둬야할거 같고.... 
고쳐지기전 까지는 url형식 잠시 텍스트로 바꿔두셔야 할거 같아요. 

참고로 url 형식 스타일은 아래처럼 적으시면 됩니다. 
.lt.wz ul.ifo li.auth a {display:inline;color:#777}

**Comment by jungbm80** [comment]
네 감사합니다!! ^^

**Comment by phiDelbak** [comment]
버그 수정된 마스터 버전 사용해 주세요.
[모바일 사용자 CSS]에 임시 조치한 .lt.wz ul.ifo li.auth.cb... 이거 지우셔도 되고요.
이제  url 형식 사용 가능합니다. 코어 버근줄 알았는데 제가 착각했어요. ㅎㅎ;;

**Comment by jungbm80** [comment]
네, 확인하였습니다~
매번 너무너무 감사드려요~
