### ISSUE TITLE
리뷰스킨 사용하면 쓰기등록하면...꺠집니다.

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#67]
아래 처럼 꺠지면서 안되는군요..스킨 사용시 별도 설정이 필요한지요?? 

![image](https://cloud.githubusercontent.com/assets/5974818/8121787/ac994e88-10eb-11e5-8a01-09177fd0a112.png)

**Comment by phiDelbak** [comment]
이거 사용 버전 안적었는데 2.5부터 사용 가능한 스킨입니다.
사용 버전 적어 둬야 겠네요^^

**Comment by ppleo** [comment]
^^ 하하 그렇군요  저도 확인하도록 하겠습니다. 빠른 답변 감사합니다.
