### ISSUE TITLE
order_type=asc 와order_type=desc 가 오류있는듯합니다.

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#68]
등록일을 누르면 order_type=asc하면 정렬이 됩니다. 하지만 다시 누르면

order_type=desc 로 변하는데 정렬이 그대로 입니다. 등록일만 아니다 제목이나 다른곳도 정렬에 문제가있는듯합니다. 확인 부탁드립니다.

참고로 임시 페이지 열어 둡니다. 이상하게 모달창쓰기도 저는 안되는군요.

**Comment by phiDelbak** [comment]
이전 버전에 있던 버그인데 최신 버전에 고쳐져 있습니다.
https://github.com/phiDelbak/Board-DX-for-XE/commit/1ebc03f9b1c9d33048445bd2c20b054c16730f9f

**Comment by ppleo** [comment]
죄송합니다. 버전 업그레이드 되었군요..헉.업그레이드 하니되네요...하하하

그런데 모달창은 왜 안될까요..ㅋㅋ

**Comment by phiDelbak** [comment]
모달 쓰기는 모달 쓰기 사용 체크 후 테스트 페이지를 열어주세요.
확인해 보겠습니다.

**Comment by ppleo** [comment]
현재 모달쓰기되여있습니다.그런데 그냥 쓰기로 가네요..하하하

![image](https://cloud.githubusercontent.com/assets/5974818/8122165/107fec4a-10f1-11e5-96dc-9f3d95a8b1ab.png)

**Comment by phiDelbak** [comment]
모달 쓰기 설정이 안되있다고 나오네요.
이거 머지? 
https://www.xpressengine.com/?module=file&act=procFileDownload&file_srl=23018171&sid=c8db990b117cf5031fe43919d09939aa&module_srl=122

이거 받으셔서 beluxe\skins\default 폴더에 넣어 바꿔보세요.

**Comment by ppleo** [comment]
넣어보니..

a:2:{i:0;s:5:"write";i:1;s:4:"view";}  가 위에 뜨는데요

**Comment by phiDelbak** [comment]
마지막으로 한번만 더 확인해주세요.
https://www.xpressengine.com/?module=file&act=procFileDownload&file_srl=23018183&sid=ee8844f74ae86127609ace097d070544&module_srl=122
이거 받으셔서 beluxe\skins\default 폴더에 넣어 바꿔보세요.

**Comment by ppleo** [comment]
넣었습니다.

--13-- 이라고 나오네요

**Comment by phiDelbak** [comment]
혹시 서버 에서 $_SERVER 이거 지원 안하나요?
그러는거 같은데... 잠시요....

**Comment by phiDelbak** [comment]
https://www.xpressengine.com/?module=file&act=procFileDownload&file_srl=23018221&sid=065e48b56eabdd24019c715c01910241&module_srl=122

이거 받으셔서 beluxe 폴더에 넣어 바꿔보세요.
추신: 위에껀 새거로 돌려놓으셔도 되요.

**Comment by phiDelbak** [comment]
추신: 위에서 바꾼 ___setting.html 새거로 다시 돌려놓으셔도 되요.

**Comment by ppleo** [comment]
바꿨습니다. 하지만 변화가...하하하하^^

**Comment by phiDelbak** [comment]
이게 익스 구버전을 체크하기위해 브라우저 검사를 하는데
ppleo님 서버에서 브라우저 정보를 무슨 이유인지 안넘겨 주네요.
(원인은 서버 설정일수도 있고..., 그런거 막는 에드온일 수 도있고...)

브라우저 정보를 안넘겨 주는경우 혹시 몰라 막아뒀습니다.
이런경우 대비해서 아무래도 자바로 체크해야 할거 같네요.

오늘은 작업하기 좀 힘들거 같고 내일 쯤에 패치 버전 올려 둘게요.
