### ISSUE TITLE
크롬에서 핫트랙 설정관련

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#69]
크롬에서 핫트랙 설정을 하게 되면 반으로 잘려나옵니다.
익스10은 정상으로 보여지는데요.

>> http://*******.co.kr/cebu

브라우저 호환성 문제일까요?

**Comment by phiDelbak** [comment]
버그 수정된 메인에 [Download Zip] 마스터 버전 받아 사용해 주세요.
이전에 문의하신 조회수 겹치는 문제와 url 형식 사용시 버그 생기는것도 모두 수정 되었습니다.

**Comment by jungbm80** [comment]
네 감사합니다^^

그리고, 업데이트시 궁금한게 있는데요.
전체 파일을 덮어 쓰는게 나을까요?
아니면 기존 파일폴더를 삭제후 새파일을 업로드 하는 것이 나을까요?
 
지금까지 업데이트할 때는 기존파일을 삭제후 또는 폴더명 변경후 새파일을 업로드하는 형태로 했는데요.
phiDelbak님께서 업데이트할때 관리자페이지를 열어놓고 하라하셔서
제 업데이트 방법에 문제가 있을까하여 여쭤봅니다~^^

**Comment by phiDelbak** [comment]
덮으셔도 큰 상관은 없어요. 
다만 삭제된 파일이 있을경우 불필요한 파일이 남을 수 있지요.
그러니 하시던대로 하시는게 더 깔끔하긴 해요 :)

관리자 페이지를 열어놓으란건 캐시꼬이면 캐시 재생성 쉽게 하시라고... 
사실 캐시꼬이면 그냥 캐시폴더 삭제해도 되요. 

결론은 둘다 편하신대로 하셔도 큰 상관은 없어요.
