### ISSUE TITLE
2.2 -> 2.5 업데이트 이후 500에러 문제점

### ISSUE THREAD

**Issue by botserv** [phiDelbak/Board-DX-for-XE#71]
게시글 작성시

게시물 작성 까지 잘되는데 완료를 누르면 500에러 현상이 일어납니다.

DX를 지우고, 캐시파일을 재생성하고 여러방법을 다해봤는데 왜 이런현상이 일어날까요./.?

[Fri Jun 12 21:48:52 2015] [error] [client 221.147.] PHP Parse error:  syntax error, unexpected T_FUNCTION in /html/modules/beluxe/beluxe.controller.php on line 31, referer: http://www./index.php?mid=recommendmusic_v2&act=dispBoardWrite
[Fri Jun 12 21:48:52 2015] [error] [client 221.147.] PHP Fatal error:  Class 'DB' not found in /html/config/func.inc.php on line 205, referer: http://www./index.php?mid=recommendmusic_v2&act=dispBoardWrite

**Comment by botserv** [comment]
2.2 버전으로 다운그레이드 하니 정상으로 돌아왔습니다.

PHP 5.2.17 XE 1.7.9 버전입니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/archive/195ac35b33a9bb21598ef9115be95be9bcc3dd5f.zip

이거 받으셔서 사용해 보세요.

**Comment by botserv** [comment]
PHP Parse error:  syntax error, unexpected '[' in /home/ncm/html/modules/beluxe/classes.item.php on line 63

해당 라인을 주석해야만 페이지가 열리고, 주석을 안할경우 사이트 전체가 백지화면(500Error)변경됩니다.

**Comment by phiDelbak** [comment]
그거 지우시면 아마 핫트랙하고 모달창 안되실거예요 ^^
수정해서 커밋 했으니 새로 마스터 버전 받아 사용하시면 됩니다.
제보 감사합니다. :)
