### ISSUE TITLE
모바일 설정의 게시판 제목/부제목 연결기호 의견

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#72]
모바일 게시판 설정에서 제목을 입력하면 뒤에 -(하이픈)이 강제로 붙게됩니다.
제목만 입력할 경우 -(하이픈)이 없으면 좋겠습니다.
 
제목에 포인트를 주고자할 때
[ ], <>, >> 와 같은 추가 기호를 붙이는데 미관상 조금 아쉬움이 있습니다~
  
그리고, 부제목 사용시 -(하이픈)을 사용하고자 할 때 부제목 앞에 인위적으로 기호를 삽입해준다면 동일한 형태로 보여주는 것이 가능합니다.
 
모바일 제목과 부제목 사이의 연결기호를 사용자 임의선택에 맡겨주시면 어떨까하여 의견드립니다^^

**Comment by phiDelbak** [comment]
참고하겠습니다 :)

**Comment by phiDelbak** [comment]
이 이슈와 같이 수정되었습니다.
https://github.com/phiDelbak/Board-DX-for-XE/commit/71fe0b18bdaa56b05d775f02d866abb9bb4c4101
