### ISSUE TITLE
new 아이콘 노출기간 설정관련 의견

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#74]
웹과 모바일에서
목록 new 아이콘 노출시간을 설정할 수 있는 입력창이 있으면 좋겠습니다~
new아이콘을 일주일정도 유지시키고 싶은데 방법이 있을까요?

**Comment by phiDelbak** [comment]
스킨/___setting.html 파일 열어보시면요
아래와 같은 부분이 있어요. 12 시간을 바꾸시면되요.

$mi->duration_new?0:$mi->duration_new = '**12**';

**Comment by jungbm80** [comment]
네! 감사합니다~ :)

**Comment by phiDelbak** [comment]
스킨에 새 글 표시 시간 옵션 추가 하였습니다. :)
https://github.com/phiDelbak/Board-DX-for-XE/commit/b869e0de333b7150919c7da218db52d650186842
