### ISSUE TITLE
모바일에서 일부 게시물이 댓글이 펼쳐지지 않는 문제

### ISSUE THREAD

**Issue by botserv** [phiDelbak/Board-DX-for-XE#75]
모바일 환경

아이폰6 (기본 인터넷, 크롬브라우저 동일)

모바일에서 작성한 게시물에 대해서 댓글에는 댓글이 펼쳐지지 않고

PC버전에서 게시물로 작성한 게시물만 댓글이 펼쳐지는 문제가 있습니다.

환경 : XE 1.7.10 PHP 5.2.17 Apache 2.2 DX 2.5(기존 2.2이하 버전에서도 이런 문제가 있었습니다.)

**Comment by phiDelbak** [comment]
갤럭시에서 테스트했을경우 문제를 찾을 수 없었습니다.
확인 가능한 url을 남겨 주시면 확인해 보겠습니다.

**Comment by botserv** [comment]
다시 확인해봤는데 PC,모바일에서의 작성 문제가 아닌듯하네요..

http://clubsound.co.kr/13010793 (댓글이 안펼쳐지는 게시물)

거의 대부분의 게시물이 댓글이 펼쳐지는데 일부 안펼쳐지는 게시물이 있네요..

스마트폰에서 작성된 게시물일 경우 댓글이 안열리고,

**Comment by botserv** [comment]
http://www.clubsound.co.kr/12857794 
게시물도 그러는데 유독 댓글이 4개이상이거나 많은 경우 안펼쳐지는 문제인 것 같습니다.

**Comment by botserv** [comment]
아 확인결과 CONORY
http://www.clubsound.co.kr/recommendmusic_v2/13010793
(열리지 않는 게시물)


./addons/show_mobile_write/ 모바일 표시 애드온이랑 충돌이 나는 것 같습니다 ㅠㅠ

http://www.conory.com/market_content/11083

해당 애드온을 이용해 댓글에 모바일 표시가 되었을경우, 열리질 않네요.

**Comment by phiDelbak** [comment]
해당 에드온이 유료라 제가 볼수없네요.
스케치북 모바일 게시판은 말씀하신대로 한번에 다 출력해 줘서 그런거 같고요.
기본 게시판에 기본 모바일 스킨에서는 어떤가요?
그게 DX와 같이 댓글을 후에 읽는 구조인데...

**Comment by botserv** [comment]
아 해당 자료가 돈을 주고 판매되는 것은 아니라 conory님 사이트에 활동하면 얻을 수 있는 자료라서
기본 XE게시판에서도 마찬가지 문제가 있는 것으로보아 DX문제는 확실히 아니네요.ㅠ

http://dlxodud.clubsound.co.kr/show_mobile_write.zip 

해당 애드온은 첨부해봤어요.

**Comment by phiDelbak** [comment]
아 유료는 아니군요. ㅎㅎ;;
그런대 기본 XE게시판에서도 마찬가지라면
제작자님이 배포 안된다고 하시던데...  제작자님이 수정하는게 맞는거 같습니다.
여의치 않으면 DX 기본 기능에 넣어드릴게요.
