### ISSUE TITLE
마스터 버전 설치 하니 

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#76]
아래 링크 스킨정보 누르니...에러가 나고 백지화 됩니다.

/com/index.php?module_srl=83349&mid=add&act=dispBeluxeAdminSkinInfo

에러문구입니다

Error Parsing Template - syntax error, unexpected '[' in template file ./modules/beluxe/tpl/skin.html

**Comment by phiDelbak** [comment]
기본 스킨 이신가요?

**Comment by ppleo** [comment]
엡 기본 스킨입니다. 그떄 그곳입니다.

http://2sis.co.kr/com/add

**Comment by phiDelbak** [comment]
음... 테스트용 관리자 비번 아디가 있어야 할거 같은대요.

**Comment by ppleo** [comment]
헉 개인적 모임 사이트라..여기에 오픈하기가...비밀글도 없군요..이메일 주시면 그쪽으로 임시 관리자 알려 드리도록 하겠습니다

**Comment by phiDelbak** [comment]
xe.phidel@gmail.com

**Comment by phiDelbak** [comment]
아 혹시 php 버전 어떻게 되세요? 5.3 이하?
이거 보시고 수정하시거나 마스터버전 다시 사용해 보세요.
https://github.com/phiDelbak/Board-DX-for-XE/commit/d40050f25ef836a28a3922b428fda5a9f6188485

**Comment by ppleo** [comment]
이제 되는군요..^^ 그런데 역시나 모달창은 안되는군요

php버전은 5.3이상입니다.

**Comment by phiDelbak** [comment]
새 마스터 버전 받아서 사용해요. 이젠 될거예요.
아마도... 안되면ㅠㅠ;;
근대 문제는 그냥 임시 조치라는거 ㅎㅎ

**Comment by ppleo** [comment]
오호 멋지게 되는군요..엡 저도 테스트 하는거라...^^

쓰는기능은 아닙니다. 감사합니다. 테스트 계정은 삭제 할게요..

**Comment by phiDelbak** [comment]
네 ㅎㅎ
