### ISSUE TITLE
포인트가 없는 게시물도 채택이 가능했으면 좋겠습니다.

### ISSUE THREAD

**Issue by botserv** [phiDelbak/Board-DX-for-XE#77]
보통 포인트가 설정되어 채택이 되면 

포인트 설정해둔 색이 바뀌어 이 답변은 채택된 답변이라
정보를 얻을 수 있구나 라는 인지를 하게 되는데

포인트 설정이 0 인 값들은 채택을 할 수 없어서
답변 채택이 되었는지 확인이 어렵습니다.

네이버 지식인도 포인트를 설정하지 않아도 채택할 수 있는 만큼
포인트가 없는 값도 채택을 할 수 있으면 좋겠습니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/8759ad1d5549af4c777bebf3df46d773089d876b
