### ISSUE TITLE
입력기 비회원 설정관련 모바일 적용의견

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#78]
스킨설정의 입력기에서 비회원 설정을
닉네임으로 선택했을 경우
웹뿐만 아니라 모바일 비회원 글쓰기(댓글달기)에도 동시 적용되었으면 좋겠습니다

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/015832f7aac9ec172e3d29e6968d4e9d9cb371ae

**Comment by jungbm80** [comment]
네 감사합니다^^
다음 버전 업데이트가 기다려집니다!
