### ISSUE TITLE
분류관리 메뉴에서 분류설정 후 옵션설정시...

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#79]
<분류관리> 메뉴에서 분류명 생성후 세부설정 메뉴를 클릭하면
<설정메뉴 레이어>가 맨앞으로 와야하는데 뒤에 배치가 된것같습니다.

 - 기본
 - 옵션
 - 그룹제한

크롬/익스 둘다 동일한 현상이 나타납니다.

**Comment by phiDelbak** [comment]
캡쳐 사진으로 설명해주세요.
잘 이해가 안갑니다.

**Comment by jungbm80** [comment]
![img](https://cloud.githubusercontent.com/assets/12507367/8248631/2f686f64-169c-11e5-98ce-1c6a32918025.png)

텍스트 클릭시 레이어메뉴가 화면이 깨진것처럼 보입니다.

**Comment by phiDelbak** [comment]
혹시 게시판 하단에 [관리 > 설정] 으로 들어가셨나요?

**Comment by jungbm80** [comment]
네. 게시판 하단에서 관리 > 설정으로 들어갔어요~

**Comment by jungbm80** [comment]
레이아웃 문제인것 같아 해당 레이아웃 관리사이트에 이슈내용 남겨놓았습니다.^^
http://simpleeye.ivyro.net/xe/gdesign_sub_qna/98398

**Comment by phiDelbak** [comment]
잘하셨어요.
어차피 둘중 하나가 고치면 되는 거니까 :)
그리고 저도 어떤 레이아웃인지 몰라 대충 고쳐봤는데 사용해보세요.

**Comment by jungbm80** [comment]
네. 신경써주셔서 감사합니다.
수정내용 확인해보았는데 레이어메뉴는 고쳐졌는데요. 다른 쪽에서 문제가 나타나서요.
분류생성 후 해당라인에 마우스 커서를 올리면 왼쪽에 세로 줄이 나타납니다.

레이아웃 빼고 테스트 해보았는데 세로줄 현상이 레이아웃 설정유무과 상관없이 나타나서요.
해당이슈가 게시판 문제가 아닌 것 같은데 괜시리 수정버전이 올라간다면
타 레이아웃 쓰시는 분들께 피해가 갈것 같습니다^^;

아쉽지만 기능상에 문제만 없다면 해당기능 사용시 xe어드민 페이지에서 설정하여 사용하겠습니다.
다시 이전 정상버전으로 복구 부탁드릴께요. 신경써주셔서 감사드려요~~

![capture2](https://cloud.githubusercontent.com/assets/12507367/8266480/5f693f16-176b-11e5-905f-0adfccf6a8c1.jpg)
