### ISSUE TITLE
모바일에서 글보기 후 하단의 목록버튼을 눌렀을 때..

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#80]
* 모바일게시판,  목록페이지 2이상 생성하여 테스트함

2번째 이상 목록페이지의 글보기 후 다시 목록으로 돌아가기 위해
하단의 <목록>버튼을 누르면 1번째 목록페이지로 이동합니다.

게시물 탐색시, 해당 목록페이지로 다시 이동해야하는 번거로움이 있어
<목록>버튼을 누르면 "이전 목록페이지"로 이동하였으면 좋겠습니다.^^

**Comment by phiDelbak** [comment]
혹시 분류 사용하시나요?

**Comment by phiDelbak** [comment]
혹시 아래 분류관리 문제로 업데이트 하셨나요?
했으면 다시 새 마스터 버전으로 받아 해주세요.
바로 전 커밋에서 파일이 누락되어 모바일 첨부에 에러가 있었습니다.

**Comment by jungbm80** [comment]
본문목록(모바일도 0)을 0으로 했을 때 모바일에서 <이전페이지>이동이 안되었는데요.
모바일 본문목록을 1로 설정하니 해당 문제가 해결되었습니다^^
카테고리추적 설정과는 별개로 모바일 본문목록 수가 영향을 미쳤던 것같습니다~

![capture](https://cloud.githubusercontent.com/assets/12507367/8266386/6cf3b41c-1767-11e5-9f57-2ff552d547dc.jpg)

**Comment by jungbm80** [comment]
마스터 버전 설치 후 관리자페이지 접속이 안됩니다
<http500내부서버오류>라고 나타납니다.

제 서버환경은 php5.5/xe1.8.3인데요
#71 이슈관련 내용과 연관이 있는 것 같습니다.

**Comment by phiDelbak** [comment]
파일 교체가 잘 안되었을 수 있으니 다시 받아 교체해 보시고요.
그래도 안되면 beluxe 폴더 삭제 후 접속해 보세요.
ie 사용하시면 
인터넷 옵션 > 고급> HTTP 오류 메시지 표시 > 체크해제
해보세요.

**Comment by jungbm80** [comment]
네~!! 감사합니다^^
