### ISSUE TITLE
모바일 간단글쓰기 기능확장 의견

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#81]
![-](https://cloud.githubusercontent.com/assets/12507367/8271517/657d9a72-1857-11e5-8f0d-866cd0e004ea.jpg)

웹의 간단글쓰기가 모바일에서도 사용가능하도록 기능이 확장되었으면 좋겠습니다.
글쓰기 버튼과 별개로 바로 목록 상단에 간단한 글쓰기 기능이 되면 어떨까 하는 생각에
의견드립니다.
(확장변수를 통한 간단한 내용입력을 통한, 설문조사 활용 및 고객데이터 입력 등 활용가능)

모바일 특성상 긴글은 작성하기가 어렵기 때문에 
짧은 글 쓰기를 유도하여 보다 액티브한 모바일 페이지 구성이 가능할것 같습니다^^

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/5a865df25b1bc314f430a2713c1f47cf9ffdcb97
