### ISSUE TITLE
목록을 갤러리로 선택했을때 모바일에서 글자 겹침현상

### ISSUE THREAD

**Issue by airbogo** [phiDelbak/Board-DX-for-XE#82]
아이폰에서 확인하였습니다. 조회수는까지는 정상적으로 표시되는데 추천수부터 날짜까지 폰트가 겹쳐저서 보입니다.

**Comment by phiDelbak** [comment]
아 이런... 꼭 한개 이상씩 옥의 티가 나오는 군요 ㅎㅎ;
(만드는건 많은대 아무래도 테스트가 부족하다보니...) 
아쉽지만 다음 버전까진 아래 방법으로 사용해 주세요.

모바일 [사용자 정의 CSS] 에 아래 코드을 적어 사용.
* .lt > li .auth .vtt {position:static}

**Comment by airbogo** [comment]
아닙니다. 계속 업데이트 해주신것만도 감사드립니다.^^

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/863369e260824aaf31e7c4919ead7d8096e1ba6d
