### ISSUE TITLE
2.7버전 업데이트 후 DX관리페이지 접속관련..

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#83]
2.7버전 업데이트 감사드립니다~
업데이트 후 DX관리페이지 접속시 500에러 메시지가 떠서 뭔가 장벽에 부딪힌 느낌이예요ㅠㅠ
(인터넷옵션 > 고급 > http 오류메시지 표시 > 체크해제하면 백지화면이 나타남)
에러메시지 후 3번의 백업/재설치 후 테스트를 통해 아래와 같은 현상을 발견하였습니다.

 - 업데이트 후 바로, 게시판 하단의 설정버튼을 누르면 DX관리자페이지가 열림
  (xe관리자 페이지의 어떠한 메뉴도 클릭하지 않고 바로 게시판 하단의 관리/설정버튼을 누름)
 - XE 관리자 페이지에 DX연동된 부분의 페이지를 열면 최초 1회에 한해 열림
 - 이후 2번째 부터는 DX관리자 페이지 접속시 500에러가 발생함

1. 서버환경: php5.5 / MySQLi 5.x
2. xe코어: 1.8.3
3. 브라우저: 익스10, 크롬

=> xe셋팅시 DB를 MySQLi로 설정하였는데 문제가 될수 있을까요?

**Comment by phiDelbak** [comment]
백지 화면이 나타나는건 보통 에드온 문제이던데...
2.5 버전은 괜찮은가요?
에드온 사용 중지해 보시고요.

그래도 발생하면 (xe.phidel@gmail.com) 로 
테스트용 관리자 하나만드셔서 아디/비번/주소 보내주세요.

**Comment by phiDelbak** [comment]
아 이거 될지 안될지 모르겠지만
루트 디렉토리에 **.htaccess** 파일 열고 맨위에 적어보세요.
그럼 메세지가 나온다는데 저도 안해봐서... 장담은 못해요.

**php_value error_reporting 22527**
**php_flag display_errors on**

끝나며 다시 지우시고요

**Comment by jungbm80** [comment]
네. 2.5 버전에서는 문제없었습니다.
애드온은 다 체크해제하고 테스트하였습니다.
테스트용 관리계정 메일로 보내드렸습니다.

그리고 .httaccess파일에 소스삽입 후 아래와 같은 오류메시지가 떴습니다.
Parse error: syntax error, unexpected '=' in /home/hosting_users/philgokr/www/files/site_design/design_0.php on line 32

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/3c83a3950e7f69597623d4825c7c83d32d399cd7

한번 마스터 버전 사용해보세요.

**Comment by phiDelbak** [comment]
test

**Comment by jungbm80** [comment]
마스터 버전 설치하였는데요.
해당이슈가 계속 발생합니다 ㅜㅜ

아래의 방법으로 업데이트하였습니다.
1) 이슈발생 상태에서 마스터버전 설치함
2) 2.5 버전으로 백업후 마스터버전 설치함

**Comment by phiDelbak** [comment]
음... 왜그러지 관리자만 2.5돌렸는데...
제가 증상이 안나타나서... 짐작이 잘 안되네요.
혹시 ftp주소 아디/비번(비번 바꾼후) 메일로 알려주실수 있나요?
그럼 고칠수 있는데...짐작으로 할려니... 좀 힘들어서요.

**Comment by jungbm80** [comment]
네! 메일드렸습니다 :)

**Comment by phiDelbak** [comment]
files\site_design\design_0.php 파일 지우니까 간단히 해결되네요 ㅎㅎㅎ;;;;

그런대 보니까 업데이트 하실때 beluxe-2-5 라고 이름을 바꾸셨나봐요.
폴더 이름이 beluxe-2-5 이래서 발생하는 버그였어요.

**Comment by jungbm80** [comment]
아~ 이제 되네요^^ 너무너무 감사합니다! ㅎㅎ
업데이트할 때 이전버전을 폴더명으로 기재해놓은 습관이 있어서요.
그게 원인이 될 지 몰랐습니다~ 앞으로 참고하겠습니다~~
