### ISSUE TITLE
간단글쓰기 상단표시, 비회원정보를 닉네임로 선택하였을 경우

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#84]
스킨정보 입력기에서 
간단글쓰기를 상단표시, 비회원 정보를 닉네임로 선택하였을 경우
Email과 Home 입력창이 없었으면 좋겠습니다.

![1](https://cloud.githubusercontent.com/assets/12507367/8286428/66baf798-1944-11e5-8a6e-c4004a19a30d.jpg)

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/85b00ba8e97b46ad179c2fd45cce6040b3deac32

**Comment by jungbm80** [comment]
의견 반영해주셔서 감사합니다 :)
