### ISSUE TITLE
모바일에서 간단글쓰기 이용하여 글내용 작성시

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#85]
1. 모바일에서 간단글쓰기를 이용하여 
내용입력창에 내용입력 및 줄바꿈을 합니다

2. 입력완료 후 본문을 확인하면 br태그가 그대로 노출됩니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/85b00ba8e97b46ad179c2fd45cce6040b3deac32

**Comment by jungbm80** [comment]
의견 반영해주셔서 감사합니다 :)
