### ISSUE TITLE
스킨정보의 첨부파일 설정시 모두 체크해제 후 저장시

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#86]
![default](https://cloud.githubusercontent.com/assets/12507367/8294969/4d3b61f4-197b-11e5-8195-1b343c4def80.jpg)

스킨정보의 첨부파일설정에서
첨부파일 기능을 사용하지 않을 경우 모두 체크해제 후 저장하면
체크해제가 되지 않고 모두 체크되어 저장되며
본문 확인시에도 모든 파일이 나타납니다.

**Comment by jungbm80** [comment]
모바일에서도 동일현상이 나타납니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/fb6c4eef8c3ba8774db73bbdbc0ab987a6198e07

**Comment by jungbm80** [comment]
의견 반영해주셔서 감사합니다 :)
