### ISSUE TITLE
모달창 글쓰기와 글보기를 취소하는 경우 (IE focus error)

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#87]
모달창 글쓰기 도중 이를 취소하는 경우 두가지 방법에 관하여
 1. 우측상단의 x표시 클릭
 2. 하단의 닫기버튼 클릭

이때 X표시를 누르는 것과 닫기버튼을 누른 후의 페이지에 변화가 생기는데요
X표시를 누르면 모달창띄우기 전의 페이지에 있는 입력창의 커서가 먹히지 않게 됩니다.
(입력창 => 검색창, 로그인창, 댓글창, 간단글쓰기 창등)

하지만, 하단의 닫기버튼을 누르면 입력기능이 이상없이 정상작동됩니다.
보통 창을 없앨때 무의식중으로 x표시를 더 잘 누르게 되는 것 같습니다.
이럴 경우 입력창에 커서가 먹히지 않게되며 새로고침을 해야합니다.

<기타>
1. 모달창 글보기 후 x표시 클릭시에도 해당 현상발생함.(닫기버튼은 정상)
    => 어쩔 때는 x표시 닫기후에도 입력창 커서가 먹히고요.
    => 어쩔 때는 안먹히는 것 같습니다.(창을 연후 5초이후에 x표시를 누르는 경우 더 많이 발생함)
2. 레이아웃을 여러개 바꿔가며 테스트하였습니다.(모두 동일증상 발생)
 
=> 큰 문제는 아니지만 해당현상을 발견하여 내용 전달드립니다^^

**Comment by phiDelbak** [comment]
이거 IE에서만 생기는 jQuery 버그인데요.
사실 이번에 고쳤어야 하는데 감빡하고 빠트렸네요. ㅎㅎ
이렇게 된거 조만간 윈도 10 나오면 엣지가 기본 브라우저로 사용될텐대요.
IE 가 점점 버려질거라? 생각해서... 윈도 10출시 후에 상태보고서 패치 하기로...

**Comment by phiDelbak** [comment]
IE에서만 발생하는 jQuery? 버그인대요.
이번에 고치려 했는데 까먹었네요 ㅎㅎ;;

이렇게 된거 조만간 윈10 출시되면 기본 브라우저가 **엣지**로 바뀔텐데요.
그러면 점점 IE가 버려지겠죠?  Active X 때문에 아닐거고 같고...
아무튼 윈10 출시 후 상태봐서 수정할게요. (영 찝찝하면 내일 당장이라도 패치될지도...)

**Comment by phiDelbak** [comment]
급한대로 쓸수있는 해결법 적어드릴게요.
아래 코드를 **모듈설정 > 기타 > 하단 내용** 에 적어주시면 해결가능합니다.
>
&lt;script>
jQuery(document).on('click','.pid_modal-head',function(){jQuery(this).prev().click()});
&lt;/script>
&lt;style>
.pid_modal-close{display:none}
.pid_modal-head:after{content:"X";position:absolute;top:10px;right:10px;cursor:pointer;}
&lt;/style>

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/24470fa1b1d1a253e48a73cb3422cf89f32f7972

**Comment by jungbm80** [comment]
아~ 1.8.3버전 설치하였는데 수정되었네요~ㅎㅎ
근데 검정색바 전체가 x버튼으로 작동이 되는데
이전 버튼형태가 디자인적으로는 더 이쁜 것 같습니다~ㅎㅎ
작은 부분하나까지 신경써주셔서 너무 감사드려요^^
