### ISSUE TITLE
모바일 본문 글제목 크기설정 관련

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#88]
모바일 본문 글제목 크기가 조금 큰 것 같은 느낌이 들어서요.
게시판 제목의 크기수준 정도로 사이즈를 변경하고(줄이고) 싶습니다.
팁좀 부탁드릴께요~

**Comment by phiDelbak** [comment]
사용자 css에
**.pn.ts h2{font-size:12px}**

**Comment by jungbm80** [comment]
네. 감사합니다 :)
