### ISSUE TITLE
랜덤 글 기능이 있으면 좋을듯합니다.

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#89]
게시글 목록들이 랜덤으로 바뀌는 기능입니다.

사용시 정보글들이 섞여서 예전글도 찾아 볼수 있으면 좋을 듯합니다.

좋은 글들은 뒤에 잊혀져서 기억하기 힘든데요..이기능이 있으면 사람들이 다 다른 글을 볼수 있어서 재미있는 기능이 될수 있을듯합니다.

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/d64b00134de28b9475c3f577936a47bb9824472a
