### ISSUE TITLE
기능 개선 문의

### ISSUE THREAD

**Issue by botserv** [phiDelbak/Board-DX-for-XE#90]
최근에 답변 채택률이 표시되는 것 너무 좋더라구요~!

그래서, 답변자의 답변 선택횟수, 등급을 지식인 처럼 
표시될 수 있으면 좋겠습니다..

이렇게 되면 답변 갯수에 따라 칭호같은걸 부여해주면(지식인처럼요) 답변을 더 
열심히 작성하는데 도움이 될 것 같아요..

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/1c5c01f267399296ae1ceafa57fd4f13c52eb0c6

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/63093ca3ddbb70489a2a8dc660a473676e7c3835

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/f9ed2700d5ef3395b735182be1bbc94843d68a3e
