### ISSUE TITLE
태그 버튼이 사라지지 않습니다.

### ISSUE THREAD

**Issue by ppleo** [phiDelbak/Board-DX-for-XE#91]
입력기에서 태그 사용 안함으로 해 두었는데요..

리스트에 검색옆에 태그 버튼이 사라지지 않고 나옵니다. ^^ 확인 부탁드립니다.

**Comment by phiDelbak** [comment]
그건 태그 입력기와는 상관없어요.
그냥 현재 작성된 태그 목록을 보여주는 버튼입니다. :)

**Comment by ppleo** [comment]
태그 입력을 안하면 태그목록이 필요 없지 않을까요..^^

아니면 태그목록 버튼 사용안함...옵션이 필요 할 듯합니다.

**Comment by phiDelbak** [comment]
제가 올린 에드온중에 해시태그 에드온이라고 있어요.
그거 사용하시면 태그가 입력되요.

태그목록 버튼 사용안함... 옵션 생각해본적이 있는데...
그거 빠지면 왠지 허전해 보여서...  미관상 그냥 두었어요. :)

특별히 그게 보이면 안되는 이유가 있으신가요?
꼭 필요하시다면 다음 버전에 추가할게요.

**Comment by ppleo** [comment]
아 그렇군요..^^ 해시태그가 거기에 나올수 있군요. 그럼 있을 필요가 있겠네요..
