### ISSUE TITLE
등급 표시?

### ISSUE THREAD

**Issue by botserv** [phiDelbak/Board-DX-for-XE#94]
1.7.10 버전 PHP 5.3 환경입니다.

2.8로 넘어오면서 답변자에 대한 등급 패치도 이루어진 것으로 아는데

http://www.clubsound.co.kr/13252740

보면 답변자의 등급 표시가 나타나지 않더라구요

설정도 찾아봤는데 등급이란 키워드가 없는데

어디서 설정해줘야할까요..?

**Comment by botserv** [comment]
아 확인해봤는데 2.8 적용후 부터 견습생 등의 표시가 적용되네요..

기존글도 표시되는 줄 알았습니다.

견습 등의 표시 여부는 어떻게 확인할 수 있고 따로 값을 조정할 수 있는 것인가요..?

**Comment by phiDelbak** [comment]
등급은 채택된 수에 따라서 등급이 결정됩니다.
따로 값을 조정할 수는 없어요.
