### ISSUE TITLE
[긴급] 채택시 포인트가 2번 적립되는 현상.

### ISSUE THREAD

**Issue by botserv** [phiDelbak/Board-DX-for-XE#96]
2015-07-05 17:41:37	적립	+100	beluxe (100) up by 정회원카일	5474
2015-07-05 17:35:27	적립	+100	beluxe (100) up by 정회원카일	5374

이런식으로 두번이나 적립되는 문제가 있습니다.

이로인해서 악용하는 유저들이 있어서 긴급히 패치를 부탁드립니다.

015-07-08 14:27:32	차감	-10	"애타게 한곡찾고있어요..." 게시물 등록 (-10) down	279

그리고 채택한 이용자에게 적립을 해줘야하는데 채택이용자에게 적립이 안되는 문제도 찾았습니다.

소스가 채택한 이용자에게 나머지를 줘야하는데

답변한이용자에게 2번들어오는 것 같습니다.

그리고 하나의 PC에서 두개의 브라우저를 이용해 테스트를 해봤는데
관리자기 때문에 지속적으로 채택이 되는 것이겠죠..?

그리고 채택시 prompt창이 뜨는데 감사메시지를 전달해주세요 라고 한글로 표시되면
더 좋겠습니다!

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/8c026d53f2e7a7be35ee8b4388af25d5d911aa4b
