### ISSUE TITLE
간단글쓰기시 확장변수 위/아래 구분선 관련..

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#97]
![default](https://cloud.githubusercontent.com/assets/12507367/8638552/6a5d08b2-28fa-11e5-86d3-051f4693013d.jpg)

간단글쓰기시 확장변수의 위 아래로 구분선이 있는데요.
개인적인 생각으로는 구분선이 불필요한 것같아서요^^;;
혹시 의도하신바가 있으신건가요?

그리고, 2.8버전에서의 추가입력숨김(확장변수 선택시) 기능이
간단글쓰기시에도 적용되었으면 좋겠습니다~

**Comment by phiDelbak** [comment]
그냥 너무 딱딱 붙어있어서 답답해 보여서요 :)

불필요 하시면 
_etc.simplewrite.html 파일에서 아래 코드를 찾아 지우시면 없어져요.
&lt;li>&lt;hr />&lt;/li>

다른 방법으로는 [사용자 CSS] 에...
#siWrt.scSimWrt .scWul li hr {display:none}

**Comment by jungbm80** [comment]
네 감사합니다^^
계속 보다보니 또 줄이 있는 것도 괜찮아보입니다~
