### ISSUE TITLE
핫트랙설정 후 컬럼설정에서 "제목" 체크해제시

### ISSUE THREAD

**Issue by jungbm80** [phiDelbak/Board-DX-for-XE#99]
2.8버전 업그레이드 후
핫트랙사용 설정 후 DX관리자페이지의 컬럼설정에서 "제목" 체크해제하면
목록의 게시글이 클릭이 안됩니다.

혹시 제목을 노출하지 않고, 컬럼명으로만 게시판 목록을 구성하고자 할때
핫트랙 기능을 이용하여 해당게시물을 열어볼수 있는 방법이 있을까요?

**Comment by phiDelbak** [comment]
https://github.com/phiDelbak/Board-DX-for-XE/commit/9291b9661bba8f14ada58d8328c182bce37a936b

**Comment by jungbm80** [comment]
의견 반영해주셔서 감사합니다.
업그레이드하였는데 클릭이 잘 되서 너무 좋습니다^^
